export const CATEGORIES = [
  { id: 'all', label: 'Wszystkie' },
  { id: 'sniadanie', label: 'Śniadanie' },
  { id: 'obiad', label: 'Obiad' },
  { id: 'kolacja', label: 'Kolacja' },
  { id: 'przekaska', label: 'Przekąska' },
]

export const TAGS = [
  { id: 'wysokobialkowe', label: 'Wysokobiałkowe' },
  { id: 'redukcja', label: 'Redukcja' },
  { id: 'masa', label: 'Masa' },
  { id: 'wegetarianskie', label: 'Wegetariańskie' },
  { id: 'szybkie', label: 'Szybkie' },
]

export const RECIPES = [
  {
    id: 'owsianka-proteinowa',
    title: 'Owsianka proteinowa z bananem',
    category: 'sniadanie',
    tags: ['wysokobialkowe', 'masa', 'wegetarianskie'],
    prepTime: 10,
    servings: 1,
    macros: { calories: 580, protein: 40, carbs: 72, fat: 14 },
    ingredients: [
      '80 g płatków owsianych',
      '1 banan (ok. 120 g)',
      '30 g odżywki białkowej (smak waniliowy lub czekoladowy)',
      '250 ml mleka 2%',
      '20 g masła orzechowego',
      'Szczypta cynamonu',
    ],
    steps: [
      'Mleko podgrzej w garnuszku lub mikrofalówce przez 2 minuty.',
      'Wsyp płatki owsiane i gotuj na małym ogniu przez 3–5 minut, mieszając co jakiś czas.',
      'Zdejmij z ognia, dodaj odżywkę białkową i dokładnie wymieszaj, żeby nie było grudek.',
      'Przełóż do miski. Na wierzchu ułóż pokrojony banan i masło orzechowe.',
      'Posyp cynamonem i podawaj od razu.',
    ],
  },
  {
    id: 'omlet-z-bialek',
    title: 'Omlet z białek z warzywami',
    category: 'sniadanie',
    tags: ['wysokobialkowe', 'redukcja', 'szybkie'],
    prepTime: 10,
    servings: 1,
    macros: { calories: 220, protein: 28, carbs: 8, fat: 8 },
    ingredients: [
      '6 białek jajek',
      '1 całe jajko',
      '100 g szpinaku baby',
      '80 g papryki czerwonej',
      '5 ml oliwy z oliwek',
      'Sól i pieprz do smaku',
    ],
    steps: [
      'Białka i całe jajko wbij do miski, dopraw solą i pieprzem, roztrzep widelcem.',
      'Patelnię rozgrzej na średnim ogniu, dodaj oliwę.',
      'Wrzuć paprykę pokrojoną w kostkę i smaż 2 minuty.',
      'Dodaj szpinak i smaż jeszcze minutę, aż zwiędnie.',
      'Wlej masę jajeczną równomiernie na patelnię. Smaż 2–3 minuty pod przykryciem, aż wierzch się zetnie.',
      'Złóż omlet na pół i przełóż na talerz.',
    ],
  },
  {
    id: 'twarog-z-jagodami',
    title: 'Twaróg z jagodami i granolą',
    category: 'sniadanie',
    tags: ['redukcja', 'wegetarianskie', 'szybkie'],
    prepTime: 5,
    servings: 1,
    macros: { calories: 320, protein: 26, carbs: 40, fat: 5 },
    ingredients: [
      '200 g twarogu półtłustego',
      '100 g jagód (świeżych lub mrożonych)',
      '30 g granoli',
      '1 łyżeczka miodu',
    ],
    steps: [
      'Twaróg przełóż do miski.',
      'Jeśli jagody są mrożone, rozłóż je wcześniej lub podgrzej 30 sekund w mikrofalówce.',
      'Ułóż jagody na twarogu, posyp granolą.',
      'Skrop miodem i podawaj od razu.',
    ],
  },
  {
    id: 'jajecznica-z-lososiem',
    title: 'Jajecznica z łososiem na chlebie razowym',
    category: 'sniadanie',
    tags: ['wysokobialkowe', 'masa'],
    prepTime: 10,
    servings: 1,
    macros: { calories: 480, protein: 38, carbs: 28, fat: 22 },
    ingredients: [
      '3 jajka',
      '80 g łososia wędzonego',
      '2 kromki chleba razowego (ok. 70 g)',
      '5 g masła',
      'Sól, pieprz, koperek do smaku',
    ],
    steps: [
      'Chleb włóż do tostera lub opiecz na patelni.',
      'Na patelni rozgrzej masło na małym ogniu.',
      'Wbij jajka, dopraw solą i pieprzem. Mieszaj drewnianą łyżką do uzyskania kremowej konsystencji — ok. 3 minuty.',
      'Zdejmij z ognia, gdy jajecznica jest jeszcze lekko wilgotna (dogotuje się od ciepła patelni).',
      'Ułóż jajecznicę na chlebie, na wierzchu połóż plastry łososia.',
      'Posyp koperkiem i podawaj od razu.',
    ],
  },
  {
    id: 'kurczak-z-ryzem',
    title: 'Kurczak z ryżem i brokułami',
    category: 'obiad',
    tags: ['wysokobialkowe', 'masa'],
    prepTime: 30,
    servings: 1,
    macros: { calories: 520, protein: 50, carbs: 60, fat: 8 },
    ingredients: [
      '180 g piersi kurczaka',
      '80 g ryżu białego (waga sucha)',
      '150 g brokułów',
      '10 ml oliwy z oliwek',
      'Sól, pieprz, czosnek w proszku, papryka słodka',
    ],
    steps: [
      'Ryż ugotuj według instrukcji na opakowaniu (ok. 15–18 minut).',
      'Brokuły podziel na różyczki, ugotuj na parze lub w osolonej wodzie przez 5–7 minut.',
      'Pierś kurczaka pokrój w plastry, dopraw solą, pieprzem, czosnkiem i papryką.',
      'Na patelni rozgrzej oliwę, smaż kurczaka po 4–5 minut z każdej strony, aż będzie złoty i dobrze wysmażony.',
      'Wyłóż na talerz: ryż, brokuły, kurczak. Opcjonalnie skrop oliwą i posyp przyprawami.',
    ],
  },
  {
    id: 'makaron-z-tunczykiem',
    title: 'Makaron z tuńczykiem i pomidorami',
    category: 'obiad',
    tags: ['wysokobialkowe', 'szybkie'],
    prepTime: 20,
    servings: 1,
    macros: { calories: 480, protein: 40, carbs: 64, fat: 7 },
    ingredients: [
      '80 g makaronu penne lub spaghetti (waga sucha)',
      '150 g tuńczyka w sosie własnym (1 puszka)',
      '200 g pomidorów krojonych (z puszki lub świeżych)',
      '50 g cukinii',
      '10 ml oliwy z oliwek',
      '1 ząbek czosnku',
      'Bazylia, sól, pieprz',
    ],
    steps: [
      'Makaron ugotuj al dente w osolonej wodzie według instrukcji.',
      'Na patelni rozgrzej oliwę, zeszklij przeciśnięty czosnek przez 1 minutę.',
      'Dodaj cukinię pokrojoną w półksiężyce, smaż 3 minuty.',
      'Wlej pomidory, dopraw solą, pieprzem i bazylią. Duś 5 minut.',
      'Dodaj odsączonego tuńczyka, delikatnie wymieszaj.',
      'Wymieszaj z odcedzonym makaronem i podawaj.',
    ],
  },
  {
    id: 'losos-z-ziemniakami',
    title: 'Łosoś pieczony z ziemniakami',
    category: 'obiad',
    tags: ['wysokobialkowe', 'masa'],
    prepTime: 35,
    servings: 1,
    macros: { calories: 560, protein: 40, carbs: 36, fat: 22 },
    ingredients: [
      '200 g filetu z łososia',
      '200 g ziemniaków',
      '100 g sałaty lodowej lub mieszanki sałat',
      '10 ml oliwy z oliwek',
      'Sok z połowy cytryny',
      'Sól, pieprz, koperek',
    ],
    steps: [
      'Piekarnik nagrzej do 200°C.',
      'Ziemniaki pokrój w ćwiartki, skrop oliwą, posól. Piecz 25 minut na blaszce wyłożonej papierem.',
      'Łososia ułóż w naczyniu żaroodpornym, skrop sokiem z cytryny, dopraw solą i pieprzem.',
      'Po 15 minutach pieczenia ziemniaków dodaj łososia do piekarnika. Piecz razem 18–20 minut.',
      'Podawaj z sałatą skropioną oliwą i sokiem z cytryny.',
    ],
  },
  {
    id: 'indyk-z-kasza',
    title: 'Indyk z kaszą gryczaną i surówką',
    category: 'obiad',
    tags: ['wysokobialkowe', 'redukcja'],
    prepTime: 30,
    servings: 1,
    macros: { calories: 500, protein: 48, carbs: 52, fat: 8 },
    ingredients: [
      '180 g filetu z indyka',
      '80 g kaszy gryczanej (waga sucha)',
      '100 g brokułów lub marchewki',
      '10 ml oliwy z oliwek',
      'Sól, pieprz, majeranek, czosnek',
    ],
    steps: [
      'Kaszę gryczaną ugotuj w 200 ml osolonej wody przez ok. 15 minut (aż wchłonie wodę).',
      'Brokuły ugotuj na parze lub sparz wrzątkiem przez 5 minut.',
      'Indyka pokrój w plastry, dopraw majerankiem, czosnkiem, solą i pieprzem.',
      'Smaż na patelni z oliwą po 4 minuty z każdej strony.',
      'Podawaj kaszę, warzywa i indyka obok siebie.',
    ],
  },
  {
    id: 'salatka-kurczak-awokado',
    title: 'Sałatka z grillowanym kurczakiem i awokado',
    category: 'obiad',
    tags: ['wysokobialkowe', 'redukcja', 'szybkie'],
    prepTime: 15,
    servings: 1,
    macros: { calories: 380, protein: 38, carbs: 10, fat: 20 },
    ingredients: [
      '150 g piersi kurczaka',
      '½ awokado (ok. 80 g)',
      '100 g mieszanki sałat',
      '100 g pomidorów cherry',
      '10 ml oliwy z oliwek',
      '5 ml octu balsamicznego',
      'Sól, pieprz, czosnek',
    ],
    steps: [
      'Kurczaka dopraw solą, pieprzem i czosnkiem. Grilluj na patelni grillowej lub zwykłej po 5 minut z każdej strony.',
      'Ostudź przez 2 minuty, pokrój w plastry.',
      'W misce wyłóż sałatę, pomidory cherry przekrojone na pół i awokado pokrojone w kostkę.',
      'Na wierzchu ułóż kurczaka.',
      'Polej oliwą i octem balsamicznym, dopraw solą i pieprzem.',
    ],
  },
  {
    id: 'wrap-z-kurczakiem',
    title: 'Wrap z kurczakiem i hummusem',
    category: 'kolacja',
    tags: ['wysokobialkowe', 'szybkie'],
    prepTime: 15,
    servings: 1,
    macros: { calories: 420, protein: 40, carbs: 42, fat: 9 },
    ingredients: [
      '1 tortilla pełnoziarnista',
      '120 g ugotowanej lub grillowanej piersi kurczaka',
      '40 g hummusu',
      '50 g rukoli lub sałaty',
      '50 g pomidorów',
      'Sól, pieprz',
    ],
    steps: [
      'Tortillę podgrzej na suchej patelni przez 30 sekund z każdej strony.',
      'Posmaruj hummusem.',
      'Ułóż rukolę, pokrojone pomidory i kurczaka pokrojonego w paski.',
      'Dopraw solą i pieprzem.',
      'Zawiń ciasno tortillę. Możesz przekroić na pół po przekątnej.',
    ],
  },
  {
    id: 'twarog-na-kolacje',
    title: 'Twaróg z warzywami na kolację',
    category: 'kolacja',
    tags: ['redukcja', 'wegetarianskie', 'szybkie'],
    prepTime: 5,
    servings: 1,
    macros: { calories: 200, protein: 24, carbs: 10, fat: 3 },
    ingredients: [
      '200 g twarogu chudego',
      '1 ogórek',
      '4–5 rzodkiewek',
      '2 łyżeczki szczypiorku',
      'Sól, pieprz',
      'Opcjonalnie: 1 łyżeczka oliwy',
    ],
    steps: [
      'Ogórek i rzodkiewki pokrój w plasterki lub kostkę.',
      'Szczypiorek drobno posiekaj.',
      'Wymieszaj twaróg z solą i pieprzem.',
      'Ułóż warzywa na twarogu lub wymieszaj wszystko razem.',
      'Opcjonalnie skrop oliwą z oliwek.',
    ],
  },
  {
    id: 'shake-bialkowy',
    title: 'Shake białkowy z bananem i owsianką',
    category: 'przekaska',
    tags: ['wysokobialkowe', 'masa', 'szybkie', 'wegetarianskie'],
    prepTime: 5,
    servings: 1,
    macros: { calories: 400, protein: 35, carbs: 54, fat: 6 },
    ingredients: [
      '30 g odżywki białkowej',
      '1 banan',
      '200 ml mleka 2%',
      '30 g płatków owsianych',
      '3–4 kostki lodu',
    ],
    steps: [
      'Wszystkie składniki wrzuć do blendera.',
      'Zblenduj przez 30–45 sekund na gładki koktajl.',
      'Przelej do szklanki i wypij od razu — płatki owsiane szybko gęstnieją.',
    ],
  },
]
