// Baza mikroskładników dla osób aktywnych fizycznie.
// Wartości RDA/AI podane dla dorosłych na podstawie "Norm żywienia dla populacji
// Polski" (NIZP-PZH, 2020). Kontekst dla sportowców opracowany m.in. w oparciu o
// stanowisko ACSM/AND/DC "Nutrition and Athletic Performance" (2016) oraz
// Larson-Meyer i wsp. (2018) "Micronutrients for Athletes".
// Dane mają charakter edukacyjny i nie zastępują porady lekarza/dietetyka.

export const CATEGORIES = [
  { id: 'all', label: 'Wszystkie' },
  { id: 'witaminy', label: 'Witaminy' },
  { id: 'mineraly', label: 'Minerały' },
  { id: 'kwasy', label: 'Kwasy tłuszczowe' },
]

// Poziom ryzyka niedoboru u osób aktywnych fizycznie
export const RISK_LEVELS = {
  wysokie: { label: 'Wysokie ryzyko', color: 'red' },
  umiarkowane: { label: 'Umiarkowane ryzyko', color: 'amber' },
  niskie: { label: 'Niskie ryzyko', color: 'green' },
}

export const NUTRIENTS = [
  {
    id: 'zelazo',
    name: 'Żelazo',
    symbol: 'Fe',
    category: 'mineraly',
    tagline: 'Transport tlenu i wydolność tlenowa',
    riskForActive: 'wysokie',
    rda: { men: '10 mg', women: '18 mg' },
    unit: 'mg',
    whyActive:
      'Żelazo buduje hemoglobinę, która transportuje tlen do pracujących mięśni. Nawet niedobór bez pełnej anemii (niska ferrytyna) obniża wydolność, wydłuża regenerację i powoduje uczucie „ciężkich nóg”. U sportowców dochodzi do strat żelaza przez pocenie się, mikrourazy przewodu pokarmowego i tzw. hemolizę marszową (rozpad krwinek przy uderzeniach stopy o podłoże).',
    deficiencySigns: [
      'Przewlekłe zmęczenie i spadek formy',
      'Bladość skóry i błon śluzowych',
      'Zadyszka przy wysiłku, który wcześniej był łatwy',
      'Kołatanie serca, zawroty głowy',
      'Osłabiona koncentracja i odporność',
    ],
    atRisk: [
      'Kobiety miesiączkujące',
      'Biegacze i sportowcy wytrzymałościowi',
      'Weganie i wegetarianie',
      'Osoby na dużym deficycie kalorycznym',
    ],
    sources: [
      { food: 'Wątróbka wieprzowa', amount: '18 mg / 100 g' },
      { food: 'Nasiona dyni', amount: '8 mg / 100 g' },
      { food: 'Soczewica (sucha)', amount: '7 mg / 100 g' },
      { food: 'Wołowina', amount: '2,6 mg / 100 g' },
      { food: 'Szpinak', amount: '2,7 mg / 100 g' },
    ],
    tip: 'Żelazo z produktów roślinnych (niehemowe) wchłania się znacznie gorzej. Łącz je z witaminą C (np. papryka, natka, cytrusy), a unikaj kawy i herbaty do posiłku — taniny hamują wchłanianie.',
    upperLimit: 'Nie suplementuj „na zapas”. Nadmiar żelaza jest toksyczny — suplementację wdrażaj tylko po badaniu ferrytyny i morfologii.',
    references: [
      'Sim M. i wsp. (2019), Eur J Appl Physiol — żelazo a sportowcy',
      'Normy żywienia dla populacji Polski (NIZP-PZH, 2020)',
    ],
  },
  {
    id: 'witamina-d',
    name: 'Witamina D',
    symbol: 'D',
    category: 'witaminy',
    tagline: 'Kości, siła mięśni i odporność',
    riskForActive: 'wysokie',
    rda: { men: '800–2000 IU (20–50 µg)', women: '800–2000 IU (20–50 µg)' },
    unit: 'µg',
    whyActive:
      'Witamina D reguluje gospodarkę wapniowo-fosforanową (zdrowie kości), ale ma też receptory w mięśniach — jej niedobór wiąże się z niższą siłą, gorszą regeneracją i wyższym ryzykiem kontuzji. W polskiej szerokości geograficznej skóra praktycznie nie produkuje witaminy D od października do marca, dlatego niedobory dotyczą większości populacji, także osób trenujących na siłowni (w pomieszczeniu).',
    deficiencySigns: [
      'Częste infekcje, obniżona odporność',
      'Bóle mięśni i osłabienie siły',
      'Bóle kostne, większa podatność na złamania',
      'Obniżony nastrój, spadek energii',
    ],
    atRisk: [
      'Prawie wszyscy w miesiącach jesienno-zimowych',
      'Osoby trenujące w halach/siłowniach',
      'Osoby z ciemniejszą karnacją',
      'Osoby rzadko przebywające na słońcu',
    ],
    sources: [
      { food: 'Tran / olej z wątroby dorsza', amount: '250 µg / 100 g' },
      { food: 'Węgorz', amount: '30 µg / 100 g' },
      { food: 'Łosoś', amount: '13 µg / 100 g' },
      { food: 'Żółtko jaja', amount: '5,4 µg / 100 g' },
      { food: 'Sery dojrzewające', amount: '1 µg / 100 g' },
    ],
    tip: 'Wybieraj formę D3 (cholekalcyferol) — jest skuteczniejsza niż D2. Jako witamina rozpuszczalna w tłuszczach lepiej się wchłania przyjmowana do posiłku z tłuszczem (np. z jajkiem, awokado, orzechami). Dawkę w zakresie 800–2000 IU najlepiej dobrać po badaniu poziomu 25(OH)D we krwi.',
    upperLimit: 'Górna granica bez kontroli lekarza to zwykle 4000 IU/dobę. Witamina D kumuluje się w organizmie — długotrwałe megadawki mogą prowadzić do hiperkalcemii.',
    references: [
      'Rusińska A. i wsp. (2018) — wytyczne suplementacji witaminą D dla Polski',
      'Owens D.J. i wsp. (2018), Sports Med — witamina D a sportowcy',
    ],
  },
  {
    id: 'magnez',
    name: 'Magnez',
    symbol: 'Mg',
    category: 'mineraly',
    tagline: 'Praca mięśni i metabolizm energii',
    riskForActive: 'wysokie',
    rda: { men: '400–420 mg', women: '310–320 mg' },
    unit: 'mg',
    whyActive:
      'Magnez bierze udział w ponad 300 reakcjach enzymatycznych, w tym w produkcji energii (ATP) i skurczu oraz rozkurczu mięśni. Intensywny trening zwiększa jego zapotrzebowanie i straty z potem i moczem. Niedobór objawia się m.in. skurczami, drżeniem mięśni i gorszą jakością snu, co pośrednio pogarsza regenerację.',
    deficiencySigns: [
      'Skurcze i drżenie mięśni',
      'Uczucie „kołatania” serca',
      'Problemy ze snem, drażliwość',
      'Zmęczenie i spadek wydolności',
    ],
    atRisk: [
      'Osoby intensywnie trenujące (straty z potem)',
      'Osoby na diecie ubogiej w produkty pełnoziarniste',
      'Osoby pijące dużo alkoholu',
      'Osoby na deficycie kalorycznym',
    ],
    sources: [
      { food: 'Pestki dyni', amount: '540 mg / 100 g' },
      { food: 'Gorzka czekolada 70%+', amount: '200 mg / 100 g' },
      { food: 'Migdały', amount: '270 mg / 100 g' },
      { food: 'Kasza gryczana', amount: '220 mg / 100 g' },
      { food: 'Szpinak', amount: '80 mg / 100 g' },
    ],
    tip: 'Najlepiej pokrywać zapotrzebowanie dietą (orzechy, pełne ziarna, kakao, warzywa liściaste). Jeśli suplementujesz, formy dobrze przyswajalne to cytrynian lub mleczan magnezu — tlenek wchłania się słabo.',
    upperLimit: 'Suplementacyjny nadmiar (zwykle powyżej ~350 mg z tabletek) daje efekt przeczyszczający. Z żywności przedawkowanie u zdrowych nerek praktycznie nie występuje.',
    references: [
      'Nielsen F.H. (2018), Nutrients — magnez a aktywność fizyczna',
      'Normy żywienia dla populacji Polski (NIZP-PZH, 2020)',
    ],
  },
  {
    id: 'wapn',
    name: 'Wapń',
    symbol: 'Ca',
    category: 'mineraly',
    tagline: 'Zdrowe kości i skurcz mięśni',
    riskForActive: 'umiarkowane',
    rda: { men: '1000 mg', women: '1000 mg' },
    unit: 'mg',
    whyActive:
      'Wapń to nie tylko kości — jest niezbędny do skurczu mięśni i przewodnictwa nerwowego. U osób aktywnych kluczowy jest dla zdrowia kości, zwłaszcza przy dużych obciążeniach treningowych i przy niedoborze energii (RED-S), który przyspiesza utratę masy kostnej. Szczególnie ważny dla kobiet i osób unikających nabiału.',
    deficiencySigns: [
      'Zwiększona podatność na złamania przeciążeniowe',
      'Skurcze i drętwienie',
      'Długofalowo: obniżona gęstość kości (osteopenia)',
    ],
    atRisk: [
      'Osoby nietolerujące laktozy / unikające nabiału',
      'Weganie',
      'Kobiety, zwłaszcza z zaburzeniami miesiączkowania',
      'Osoby z niską dostępnością energii (RED-S)',
    ],
    sources: [
      { food: 'Ser żółty', amount: '800 mg / 100 g' },
      { food: 'Mak', amount: '1400 mg / 100 g' },
      { food: 'Sardynki (z ośćmi)', amount: '330 mg / 100 g' },
      { food: 'Jogurt naturalny', amount: '170 mg / 100 g' },
      { food: 'Tofu (wytrącane wapniem)', amount: '350 mg / 100 g' },
      { food: 'Napoje roślinne fortyfikowane', amount: '120 mg / 100 ml' },
    ],
    tip: 'Do wchłaniania wapnia niezbędna jest odpowiednia witamina D. Osoby na diecie roślinnej powinny wybierać fortyfikowane napoje roślinne i tofu wytrącane solami wapnia.',
    upperLimit: 'Nie przekraczaj ~2500 mg/dobę łącznie. Bardzo wysokie dawki z suplementów mogą sprzyjać kamicy nerkowej i zaburzać wchłanianie żelaza i cynku.',
    references: [
      'ACSM/AND/DC Position Stand: Nutrition and Athletic Performance (2016)',
      'Normy żywienia dla populacji Polski (NIZP-PZH, 2020)',
    ],
  },
  {
    id: 'cynk',
    name: 'Cynk',
    symbol: 'Zn',
    category: 'mineraly',
    tagline: 'Odporność, regeneracja i gospodarka hormonalna',
    riskForActive: 'umiarkowane',
    rda: { men: '11 mg', women: '8 mg' },
    unit: 'mg',
    whyActive:
      'Cynk uczestniczy w syntezie białek i podziale komórek (regeneracja tkanek), w pracy układu odpornościowego oraz w gospodarce hormonalnej, w tym w utrzymaniu prawidłowego poziomu testosteronu. Jest tracony z potem, więc intensywnie trenujący mogą mieć wyższe zapotrzebowanie.',
    deficiencySigns: [
      'Częstsze i dłuższe infekcje',
      'Wolniejsze gojenie ran i regeneracja',
      'Wypadanie włosów, problemy skórne',
      'Osłabiony apetyt i zaburzenia smaku',
    ],
    atRisk: [
      'Weganie i wegetarianie (fityniany hamują wchłanianie)',
      'Osoby intensywnie się pocące',
      'Osoby na monotonnej diecie ubogiej w mięso/owoce morza',
    ],
    sources: [
      { food: 'Ostrygi', amount: '40 mg / 100 g' },
      { food: 'Wątróbka cielęca', amount: '8 mg / 100 g' },
      { food: 'Pestki dyni', amount: '7,5 mg / 100 g' },
      { food: 'Wołowina', amount: '4,8 mg / 100 g' },
      { food: 'Ser żółty', amount: '3,5 mg / 100 g' },
    ],
    tip: 'Nie łącz wysokich dawek cynku z suplementem żelaza w tym samym posiłku — konkurują o wchłanianie. Moczenie i kiełkowanie nasion roślin strączkowych zmniejsza ilość fitynianów i poprawia przyswajalność cynku.',
    upperLimit: 'Górna granica to ok. 25–40 mg/dobę. Przewlekły nadmiar cynku upośledza wchłanianie miedzi i osłabia odporność — odwrotnie do zamierzonego efektu.',
    references: [
      'Larson-Meyer D.E. i wsp. (2018), Int J Sport Nutr Exerc Metab',
      'Normy żywienia dla populacji Polski (NIZP-PZH, 2020)',
    ],
  },
  {
    id: 'witamina-b12',
    name: 'Witamina B12',
    symbol: 'B12',
    category: 'witaminy',
    tagline: 'Krew, układ nerwowy i energia',
    riskForActive: 'umiarkowane',
    rda: { men: '2,4 µg', women: '2,4 µg' },
    unit: 'µg',
    whyActive:
      'Witamina B12 jest niezbędna do produkcji czerwonych krwinek (transport tlenu) i prawidłowej pracy układu nerwowego. Jej niedobór prowadzi do anemii megaloblastycznej, która drastycznie obniża wydolność. Występuje niemal wyłącznie w produktach zwierzęcych, dlatego jest to składnik krytyczny dla wegan.',
    deficiencySigns: [
      'Zmęczenie i osłabienie (anemia)',
      'Mrowienie i drętwienie kończyn',
      'Problemy z pamięcią i koncentracją',
      'Bladość, zadyszka',
    ],
    atRisk: [
      'Weganie — obowiązkowa suplementacja',
      'Wegetarianie z niskim spożyciem nabiału i jaj',
      'Osoby starsze i po operacjach przewodu pokarmowego',
    ],
    sources: [
      { food: 'Wątróbka wołowa', amount: '60 µg / 100 g' },
      { food: 'Małże', amount: '99 µg / 100 g' },
      { food: 'Makrela', amount: '19 µg / 100 g' },
      { food: 'Wołowina', amount: '2,5 µg / 100 g' },
      { food: 'Jaja', amount: '1,3 µg / 100 g' },
    ],
    tip: 'B12 z żywności roślinnej (algi, produkty „bio”) jest zwykle nieaktywna biologicznie i nie jest wiarygodnym źródłem. Weganie powinni suplementować B12 (np. 250 µg dziennie lub 2000 µg raz w tygodniu) — to nie jest opcjonalne.',
    upperLimit: 'B12 jest rozpuszczalna w wodzie, nadmiar jest wydalany — nie ustalono górnej granicy toksyczności. Bezpieczna nawet w wysokich dawkach suplementacyjnych.',
    references: [
      'Pawlak R. i wsp. (2013) — B12 u wegan/wegetarian',
      'Normy żywienia dla populacji Polski (NIZP-PZH, 2020)',
    ],
  },
  {
    id: 'sod',
    name: 'Sód',
    symbol: 'Na',
    category: 'mineraly',
    tagline: 'Elektrolit gospodarki wodnej',
    riskForActive: 'umiarkowane',
    rda: { men: '1500 mg (AI)', women: '1500 mg (AI)' },
    unit: 'mg',
    whyActive:
      'To rzadki przypadek, w którym problemem populacyjnym jest nadmiar, ale u intensywnie pocących się sportowców straty sodu z potem bywają duże. Sód utrzymuje objętość osocza i nawodnienie oraz umożliwia przewodnictwo nerwowo-mięśniowe. Przy długich, intensywnych treningach w upale zbyt niski poziom sodu (hiponatremia z przewodnienia czystą wodą) bywa groźniejszy niż jego nadmiar.',
    deficiencySigns: [
      'Skurcze mięśni przy długim wysiłku w upale',
      'Bóle i zawroty głowy, nudności',
      'Osłabienie, dezorientacja (przy hiponatremii)',
    ],
    atRisk: [
      'Sportowcy wytrzymałościowi trenujący długo i w upale',
      'Osoby mocno się pocące („słony” pot na skórze)',
    ],
    sources: [
      { food: 'Sól kuchenna', amount: '≈39 000 mg / 100 g' },
      { food: 'Napoje izotoniczne', amount: '40–110 mg / 100 ml' },
      { food: 'Wędliny, sery', amount: 'zmiennie, wysoko' },
    ],
    tip: 'Dla większości osób cel to ograniczanie soli. Ale przy treningach dłuższych niż ~60–90 min lub w upale warto uzupełniać sód napojem izotonicznym — sama woda nie wystarczy i może rozcieńczyć elektrolity.',
    upperLimit: 'Dla ogółu populacji zaleca się poniżej 2000 mg sodu (≈5 g soli) dziennie — nadmiar sprzyja nadciśnieniu. Zwiększone zapotrzebowanie dotyczy tylko okołotreningowo intensywnie pocących się.',
    references: [
      'ACSM Position Stand: Exercise and Fluid Replacement (2007)',
      'WHO — wytyczne spożycia sodu (2012)',
    ],
  },
  {
    id: 'potas',
    name: 'Potas',
    symbol: 'K',
    category: 'mineraly',
    tagline: 'Skurcz mięśni i ciśnienie krwi',
    riskForActive: 'niskie',
    rda: { men: '3500 mg (AI)', women: '3500 mg (AI)' },
    unit: 'mg',
    whyActive:
      'Potas współpracuje z sodem w utrzymaniu równowagi wodno-elektrolitowej, przewodnictwie nerwowym i skurczu mięśni (w tym serca). Odpowiednia podaż sprzyja prawidłowemu ciśnieniu krwi. Niedobory są rzadsze niż sodu, ale duże straty z potem i moczem oraz dieta uboga w warzywa i owoce mogą je pogłębiać.',
    deficiencySigns: [
      'Osłabienie i skurcze mięśni',
      'Zaburzenia rytmu serca',
      'Zmęczenie, zaparcia',
    ],
    atRisk: [
      'Osoby jedzące mało warzyw i owoców',
      'Osoby z dużymi stratami płynów (biegunki, intensywne pocenie)',
    ],
    sources: [
      { food: 'Suszone morele', amount: '1700 mg / 100 g' },
      { food: 'Fasola biała (sucha)', amount: '1200 mg / 100 g' },
      { food: 'Awokado', amount: '485 mg / 100 g' },
      { food: 'Banan', amount: '360 mg / 100 g' },
      { food: 'Ziemniaki', amount: '420 mg / 100 g' },
    ],
    tip: 'Najlepszym źródłem są warzywa, owoce i strączki — dieta bogata w rośliny zwykle w pełni pokrywa zapotrzebowanie na potas bez suplementów.',
    upperLimit: 'Suplementów potasu nie należy przyjmować bez wskazań — u osób z chorobami nerek nadmiar potasu (hiperkaliemia) jest groźny dla serca.',
    references: [
      'EFSA (2016) — Dietary Reference Values for potassium',
      'Normy żywienia dla populacji Polski (NIZP-PZH, 2020)',
    ],
  },
  {
    id: 'witamina-c',
    name: 'Witamina C',
    symbol: 'C',
    category: 'witaminy',
    tagline: 'Odporność, kolagen i wchłanianie żelaza',
    riskForActive: 'niskie',
    rda: { men: '90 mg', women: '75 mg' },
    unit: 'mg',
    whyActive:
      'Witamina C jest przeciwutleniaczem wspierającym odporność (istotne przy dużych obciążeniach treningowych, które przejściowo obniżają odporność), niezbędnym do syntezy kolagenu (ścięgna, więzadła, skóra) i silnie zwiększającym wchłanianie żelaza niehemowego z roślin.',
    deficiencySigns: [
      'Częstsze infekcje, wolniejsze gojenie',
      'Krwawiące dziąsła, łatwe siniaczenie',
      'Zmęczenie, osłabienie tkanki łącznej',
    ],
    atRisk: [
      'Osoby jedzące mało świeżych warzyw i owoców',
      'Palacze (wyższe zapotrzebowanie)',
    ],
    sources: [
      { food: 'Papryka czerwona', amount: '140 mg / 100 g' },
      { food: 'Natka pietruszki', amount: '180 mg / 100 g' },
      { food: 'Czarna porzeczka', amount: '180 mg / 100 g' },
      { food: 'Brokuł', amount: '65 mg / 100 g' },
      { food: 'Kiwi', amount: '90 mg / 100 g' },
    ],
    tip: 'Dodanie źródła witaminy C (papryka, natka, cytrusy) do posiłku z roślinnym żelazem wyraźnie zwiększa jego wchłanianie. Uwaga: bardzo wysokie dawki antyoksydantów okołotreningowo mogą tłumić korzystne adaptacje treningowe — nie przesadzaj z megadawkami.',
    upperLimit: 'Powyżej ~1000 mg/dobę z suplementów mogą pojawić się dolegliwości żołądkowe i ryzyko kamicy nerkowej u predysponowanych. Z żywności ryzyka brak.',
    references: [
      'Braakhuis A.J., Hopkins W.G. (2015), Sports Med — antyoksydanty a sport',
      'Normy żywienia dla populacji Polski (NIZP-PZH, 2020)',
    ],
  },
  {
    id: 'kwas-foliowy',
    name: 'Foliany (B9)',
    symbol: 'B9',
    category: 'witaminy',
    tagline: 'Produkcja krwi i podziały komórek',
    riskForActive: 'niskie',
    rda: { men: '400 µg', women: '400 µg' },
    unit: 'µg',
    whyActive:
      'Foliany są potrzebne do produkcji czerwonych krwinek i syntezy DNA (podziały komórek, regeneracja). Ich niedobór, podobnie jak B12, prowadzi do anemii megaloblastycznej i spadku wydolności. Szczególnie istotne dla kobiet w wieku rozrodczym.',
    deficiencySigns: [
      'Zmęczenie i osłabienie (anemia)',
      'Bladość, zadyszka',
      'Zapalenie języka, owrzodzenia jamy ustnej',
      'Drażliwość, problemy z koncentracją',
    ],
    atRisk: [
      'Kobiety w wieku rozrodczym (i planujące ciążę — 400 µg suplementacji)',
      'Osoby jedzące mało warzyw liściastych i strączków',
      'Osoby nadużywające alkoholu',
    ],
    sources: [
      { food: 'Wątróbka', amount: '580 µg / 100 g' },
      { food: 'Soczewica (sucha)', amount: '480 µg / 100 g' },
      { food: 'Szpinak', amount: '190 µg / 100 g' },
      { food: 'Szparagi', amount: '150 µg / 100 g' },
      { food: 'Ciecierzyca', amount: '170 µg / 100 g' },
    ],
    tip: 'Foliany są wrażliwe na wysoką temperaturę i światło — długie gotowanie warzyw niszczy ich sporą część. Gotuj krótko, na parze, i jedz część warzyw na surowo.',
    upperLimit: 'Górna granica z suplementów i żywności wzbogacanej to 1000 µg/dobę — nadmiar syntetycznego kwasu foliowego może maskować niedobór B12.',
    references: [
      'EFSA (2014) — Dietary Reference Values for folate',
      'Normy żywienia dla populacji Polski (NIZP-PZH, 2020)',
    ],
  },
  {
    id: 'jod',
    name: 'Jod',
    symbol: 'I',
    category: 'mineraly',
    tagline: 'Tarczyca i tempo metabolizmu',
    riskForActive: 'niskie',
    rda: { men: '150 µg', women: '150 µg' },
    unit: 'µg',
    whyActive:
      'Jod jest budulcem hormonów tarczycy, które regulują tempo przemiany materii, produkcję energii i termoregulację. Zaburzenia pracy tarczycy przekładają się bezpośrednio na energię do treningu, regenerację i kompozycję ciała.',
    deficiencySigns: [
      'Zmęczenie, senność, uczucie zimna',
      'Przyrost masy ciała mimo diety',
      'Powiększenie tarczycy (wole)',
      'Suchość skóry, wypadanie włosów',
    ],
    atRisk: [
      'Osoby unikające soli jodowanej i nabiału',
      'Weganie (mało naturalnych źródeł jodu)',
    ],
    sources: [
      { food: 'Sól jodowana', amount: '≈2300 µg / 100 g' },
      { food: 'Dorsz', amount: '110 µg / 100 g' },
      { food: 'Wodorosty nori', amount: 'zmiennie, bardzo wysoko' },
      { food: 'Mleko', amount: '13 µg / 100 ml' },
      { food: 'Jaja', amount: '20 µg / 100 g' },
    ],
    tip: 'W Polsce sól kuchenna jest obowiązkowo jodowana — to główne źródło jodu w diecie. Osoby ograniczające sól i weganie powinni zadbać o inne źródła (ryby, nabiał, kontrolowane porcje alg).',
    upperLimit: 'Górna granica to 600 µg/dobę. Uwaga na wodorosty — potrafią zawierać ekstremalnie zmienne, czasem toksyczne ilości jodu.',
    references: [
      'EFSA (2014) — Dietary Reference Values for iodine',
      'Normy żywienia dla populacji Polski (NIZP-PZH, 2020)',
    ],
  },
  {
    id: 'witamina-e',
    name: 'Witamina E',
    symbol: 'E',
    category: 'witaminy',
    tagline: 'Ochrona antyoksydacyjna komórek',
    riskForActive: 'niskie',
    rda: { men: '10 mg', women: '8 mg' },
    unit: 'mg',
    whyActive:
      'Witamina E to główny przeciwutleniacz rozpuszczalny w tłuszczach — chroni błony komórkowe, w tym komórek mięśniowych, przed stresem oksydacyjnym generowanym przez intensywny wysiłek. Współdziała z witaminą C w układzie antyoksydacyjnym organizmu.',
    deficiencySigns: [
      'Niedobór jest rzadki u zdrowych osób',
      'Osłabienie mięśni (przy skrajnym niedoborze)',
      'Zaburzenia neurologiczne (przy zaburzeniach wchłaniania tłuszczów)',
    ],
    atRisk: [
      'Osoby z zaburzeniami wchłaniania tłuszczów',
      'Diety skrajnie niskotłuszczowe',
    ],
    sources: [
      { food: 'Olej z kiełków pszenicy', amount: '150 mg / 100 g' },
      { food: 'Pestki słonecznika', amount: '35 mg / 100 g' },
      { food: 'Migdały', amount: '26 mg / 100 g' },
      { food: 'Orzechy laskowe', amount: '15 mg / 100 g' },
      { food: 'Oliwa z oliwek', amount: '14 mg / 100 g' },
    ],
    tip: 'Zapotrzebowanie łatwo pokryć dietą bogatą w orzechy, pestki i dobre oleje roślinne. Jako witamina rozpuszczalna w tłuszczach wymaga obecności tłuszczu w posiłku do wchłonięcia.',
    upperLimit: 'Górna granica z suplementów to ok. 300 mg/dobę (α-tokoferol). Przewlekłe megadawki mogą zwiększać ryzyko krwawień i tłumić adaptacje treningowe.',
    references: [
      'EFSA (2015) — Dietary Reference Values for vitamin E',
      'Normy żywienia dla populacji Polski (NIZP-PZH, 2020)',
    ],
  },
  {
    id: 'witamina-a',
    name: 'Witamina A',
    symbol: 'A',
    category: 'witaminy',
    tagline: 'Wzrok, odporność i regeneracja tkanek',
    riskForActive: 'niskie',
    rda: { men: '900 µg', women: '700 µg' },
    unit: 'µg',
    whyActive:
      'Witamina A (retinol oraz prowitamina — beta-karoten) jest niezbędna dla widzenia, pracy układu odpornościowego oraz prawidłowego wzrostu i różnicowania komórek, w tym regeneracji nabłonków i skóry. Jako antyoksydant (beta-karoten) wspiera ochronę komórek przed stresem oksydacyjnym generowanym przez trening.',
    deficiencySigns: [
      'Pogorszenie widzenia o zmierzchu („kurza ślepota”)',
      'Suchość skóry i błon śluzowych',
      'Częstsze infekcje (osłabiona odporność)',
      'Wolniejsza regeneracja nabłonków',
    ],
    atRisk: [
      'Osoby jedzące mało warzyw pomarańczowych i zielonych',
      'Diety skrajnie niskotłuszczowe (gorsze wchłanianie)',
      'Osoby z zaburzeniami wchłaniania tłuszczów',
    ],
    sources: [
      { food: 'Wątróbka wołowa', amount: '9400 µg / 100 g' },
      { food: 'Marchew', amount: '830 µg RAE / 100 g' },
      { food: 'Batat', amount: '710 µg RAE / 100 g' },
      { food: 'Szpinak', amount: '470 µg RAE / 100 g' },
      { food: 'Masło', amount: '680 µg / 100 g' },
    ],
    tip: 'Beta-karoten z warzyw wchłania się znacznie lepiej z dodatkiem tłuszczu (np. marchewka z oliwą) i po obróbce termicznej. To bezpieczna forma — organizm przekształca w witaminę A tylko tyle, ile potrzebuje.',
    upperLimit: 'Górna granica dla gotowego retinolu to 3000 µg/dobę. Uwaga: wątróbka jest bardzo bogata w retinol — nie jedz jej codziennie. Nadmiar retinolu (nie beta-karotenu) jest toksyczny i groźny w ciąży.',
    references: [
      'EFSA (2015) — Dietary Reference Values for vitamin A',
      'Normy żywienia dla populacji Polski (NIZP-PZH, 2020)',
    ],
  },
  {
    id: 'selen',
    name: 'Selen',
    symbol: 'Se',
    category: 'mineraly',
    tagline: 'Antyoksydant i wsparcie tarczycy',
    riskForActive: 'niskie',
    rda: { men: '55 µg', women: '55 µg' },
    unit: 'µg',
    whyActive:
      'Selen wchodzi w skład enzymów antyoksydacyjnych (peroksydazy glutationowej), które neutralizują wolne rodniki powstające podczas intensywnego wysiłku. Wspiera też pracę tarczycy (aktywacja hormonów) oraz układ odpornościowy. Zawartość selenu w żywności zależy od gleby, dlatego podaż bywa zmienna.',
    deficiencySigns: [
      'Osłabiona odporność antyoksydacyjna',
      'Zaburzenia pracy tarczycy',
      'Osłabienie mięśni (przy skrajnym niedoborze)',
      'Wypadanie włosów, łamliwość paznokci',
    ],
    atRisk: [
      'Osoby na diecie ubogiej w ryby, jaja i orzechy',
      'Osoby żyjące na terenach o glebie ubogiej w selen',
    ],
    sources: [
      { food: 'Orzechy brazylijskie', amount: '1900 µg / 100 g' },
      { food: 'Tuńczyk', amount: '80 µg / 100 g' },
      { food: 'Nasiona słonecznika', amount: '53 µg / 100 g' },
      { food: 'Jaja', amount: '30 µg / 100 g' },
      { food: 'Wątróbka', amount: '40 µg / 100 g' },
    ],
    tip: 'Już 1–2 orzechy brazylijskie dziennie pokrywają zapotrzebowanie na selen — ale nie jedz ich garściami, bo łatwo o przedawkowanie. To najprostszy „naturalny suplement” selenu.',
    upperLimit: 'Górna granica to 300–400 µg/dobę. Nadmiar selenu (selenoza) objawia się m.in. czosnkowym zapachem oddechu, wypadaniem włosów i kruchością paznokci.',
    references: [
      'EFSA (2014) — Dietary Reference Values for selenium',
      'Normy żywienia dla populacji Polski (NIZP-PZH, 2020)',
    ],
  },
  {
    id: 'miedz',
    name: 'Miedź',
    symbol: 'Cu',
    category: 'mineraly',
    tagline: 'Metabolizm żelaza i tkanka łączna',
    riskForActive: 'niskie',
    rda: { men: '0,9 mg', women: '0,9 mg' },
    unit: 'mg',
    whyActive:
      'Miedź jest potrzebna do prawidłowego wykorzystania żelaza (produkcja czerwonych krwinek i transport tlenu), tworzenia kolagenu i elastyny (ścięgna, więzadła, naczynia) oraz działania enzymów antyoksydacyjnych. Niedobór bywa skutkiem długotrwałej, nadmiernej suplementacji cynku, który blokuje jej wchłanianie.',
    deficiencySigns: [
      'Anemia niereagująca na żelazo',
      'Osłabienie tkanki łącznej i naczyń',
      'Obniżona odporność',
      'Zaburzenia neurologiczne (przy skrajnym niedoborze)',
    ],
    atRisk: [
      'Osoby długo suplementujące wysokie dawki cynku',
      'Osoby po operacjach bariatrycznych / z zaburzeniami wchłaniania',
    ],
    sources: [
      { food: 'Wątróbka cielęca', amount: '12 mg / 100 g' },
      { food: 'Ostrygi', amount: '4 mg / 100 g' },
      { food: 'Orzechy nerkowca', amount: '2,2 mg / 100 g' },
      { food: 'Kakao / gorzka czekolada', amount: '1,8 mg / 100 g' },
      { food: 'Nasiona słonecznika', amount: '1,8 mg / 100 g' },
    ],
    tip: 'Jeśli suplementujesz cynk w wyższych dawkach przez dłuższy czas, zadbaj o źródła miedzi (orzechy, kakao, owoce morza) lub wybierz suplement z korzystną proporcją cynku do miedzi.',
    upperLimit: 'Górna granica to 5 mg/dobę. Nadmiar miedzi jest hepatotoksyczny — nie suplementuj jej bez wskazań.',
    references: [
      'EFSA (2015) — Dietary Reference Values for copper',
      'Normy żywienia dla populacji Polski (NIZP-PZH, 2020)',
    ],
  },
  {
    id: 'omega-3',
    name: 'Kwasy omega-3 (EPA + DHA)',
    symbol: 'ω3',
    category: 'kwasy',
    tagline: 'Regeneracja, stawy i przeciwzapalne działanie',
    riskForActive: 'umiarkowane',
    rda: { men: '≥250 mg EPA+DHA', women: '≥250 mg EPA+DHA' },
    unit: 'mg',
    whyActive:
      'Wielonienasycone kwasy omega-3 (EPA i DHA) mają działanie przeciwzapalne, co u osób trenujących może wspierać regenerację, zmniejszać odczuwaną bolesność mięśni (DOMS) i wspomagać zdrowie stawów. Są też kluczowe dla serca i mózgu. Dieta zachodnia jest zwykle uboga w omega-3, a bogata w prozapalne omega-6 — stąd częsty względny niedobór.',
    deficiencySigns: [
      'Niekorzystny profil zapalny organizmu',
      'Sucha skóra, problemy ze stawami',
      'Gorsza koncentracja i nastrój (przy długim niedoborze)',
    ],
    atRisk: [
      'Osoby jedzące ryby rzadziej niż 1–2 razy w tygodniu',
      'Weganie i wegetarianie (brak EPA/DHA z ryb)',
      'Diety oparte głównie o oleje bogate w omega-6',
    ],
    sources: [
      { food: 'Makrela', amount: '2600 mg EPA+DHA / 100 g' },
      { food: 'Łosoś', amount: '2200 mg EPA+DHA / 100 g' },
      { food: 'Sardynki', amount: '1500 mg EPA+DHA / 100 g' },
      { food: 'Siemię lniane (ALA)', amount: '22 000 mg ALA / 100 g' },
      { food: 'Orzechy włoskie (ALA)', amount: '9000 mg ALA / 100 g' },
    ],
    tip: 'Roślinne ALA (siemię, orzechy włoskie, olej rzepakowy) organizm tylko w niewielkim stopniu przekształca w aktywne EPA/DHA. Weganie i osoby niejedzące ryb powinni rozważyć suplement omega-3 z alg (bezpośrednie źródło DHA/EPA).',
    upperLimit: 'Suplementacja EPA+DHA do ok. 3–5 g/dobę jest uznawana za bezpieczną. Bardzo wysokie dawki mogą wydłużać czas krzepnięcia — ostrożnie przy lekach przeciwzakrzepowych.',
    references: [
      'EFSA (2012) — DRV for EPA + DHA (250 mg/dobę)',
      'Rodacki C.L. i wsp. (2012) — omega-3 a funkcja mięśni',
    ],
  },
  {
    id: 'witamina-k',
    name: 'Witamina K',
    symbol: 'K',
    category: 'witaminy',
    tagline: 'Krzepnięcie krwi i zdrowie kości',
    riskForActive: 'niskie',
    rda: { men: '65 µg (AI)', women: '55 µg (AI)' },
    unit: 'µg',
    whyActive:
      'Witamina K jest niezbędna do prawidłowego krzepnięcia krwi oraz do mineralizacji kości — aktywuje osteokalcynę, białko wiążące wapń w tkance kostnej. Dla osób aktywnych, szczególnie obciążających układ kostny, wspiera zdrowie kości wspólnie z wapniem i witaminą D.',
    deficiencySigns: [
      'Skłonność do siniaków i przedłużonego krwawienia',
      'Długofalowo: gorsza mineralizacja kości',
      'Niedobór u zdrowych dorosłych jest rzadki',
    ],
    atRisk: [
      'Osoby jedzące mało warzyw liściastych',
      'Osoby po długiej antybiotykoterapii',
      'Osoby z zaburzeniami wchłaniania tłuszczów',
    ],
    sources: [
      { food: 'Natka pietruszki', amount: '1600 µg / 100 g' },
      { food: 'Jarmuż', amount: '700 µg / 100 g' },
      { food: 'Szpinak', amount: '480 µg / 100 g' },
      { food: 'Natto (fermentowana soja, K2)', amount: '1000 µg / 100 g' },
      { food: 'Brokuł', amount: '140 µg / 100 g' },
    ],
    tip: 'Witamina K rozpuszcza się w tłuszczach — jedz zielone warzywa z dodatkiem oleju lub oliwy. Forma K2 (z produktów fermentowanych i nabiału) szczególnie wspiera kierowanie wapnia do kości.',
    upperLimit: 'Nie ustalono górnej granicy toksyczności dla naturalnej witaminy K. Uwaga: osoby przyjmujące leki przeciwzakrzepowe (np. warfarynę) muszą utrzymywać stałą podaż witaminy K i skonsultować dietę z lekarzem.',
    references: [
      'EFSA (2017) — Dietary Reference Values for vitamin K',
      'Normy żywienia dla populacji Polski (NIZP-PZH, 2020)',
    ],
  },
  {
    id: 'witamina-b1',
    name: 'Witamina B1 (tiamina)',
    symbol: 'B1',
    category: 'witaminy',
    tagline: 'Przemiana węglowodanów w energię',
    riskForActive: 'umiarkowane',
    rda: { men: '1,3 mg', women: '1,1 mg' },
    unit: 'mg',
    whyActive:
      'Tiamina jest kluczowa w przemianie węglowodanów w energię (ATP) oraz w pracy układu nerwowego. Ponieważ osoby aktywne spalają więcej węglowodanów i mają wyższą przemianę energii, ich zapotrzebowanie na tiaminę rośnie proporcjonalnie do spożycia kalorii z węglowodanów.',
    deficiencySigns: [
      'Zmęczenie i spadek wydolności',
      'Drażliwość, problemy z koncentracją',
      'Skurcze i osłabienie mięśni',
      'Zaburzenia neurologiczne (przy skrajnym niedoborze)',
    ],
    atRisk: [
      'Osoby o wysokim spożyciu kalorii z przetworzonych węglowodanów',
      'Osoby nadużywające alkoholu',
      'Diety oparte głównie o oczyszczone zboża',
    ],
    sources: [
      { food: 'Nasiona słonecznika', amount: '1,5 mg / 100 g' },
      { food: 'Wieprzowina', amount: '0,9 mg / 100 g' },
      { food: 'Płatki owsiane', amount: '0,5 mg / 100 g' },
      { food: 'Kasza gryczana', amount: '0,4 mg / 100 g' },
      { food: 'Groch (suchy)', amount: '0,8 mg / 100 g' },
    ],
    tip: 'Tiamina jest wrażliwa na wysoką temperaturę i rozpuszcza się w wodzie — część ginie w wodzie z gotowania. Wybieraj pełnoziarniste zboża zamiast oczyszczonych, by dostarczyć jej więcej.',
    upperLimit: 'Rozpuszczalna w wodzie — nadmiar jest wydalany z moczem, nie ustalono górnej granicy toksyczności.',
    references: [
      'EFSA (2016) — Dietary Reference Values for thiamin',
      'Normy żywienia dla populacji Polski (NIZP-PZH, 2020)',
    ],
  },
  {
    id: 'witamina-b2',
    name: 'Witamina B2 (ryboflawina)',
    symbol: 'B2',
    category: 'witaminy',
    tagline: 'Produkcja energii i ochrona antyoksydacyjna',
    riskForActive: 'umiarkowane',
    rda: { men: '1,3 mg', women: '1,1 mg' },
    unit: 'mg',
    whyActive:
      'Ryboflawina wchodzi w skład koenzymów (FAD, FMN) niezbędnych do produkcji energii z węglowodanów, tłuszczów i białek oraz wspiera regenerację glutationu — ważnego antyoksydantu. Badania sugerują, że intensywny wysiłek zwiększa zapotrzebowanie na ryboflawinę, a najbardziej narażone są osoby unikające nabiału.',
    deficiencySigns: [
      'Pęknięcia w kącikach ust, stany zapalne warg',
      'Zapalenie języka, zmiany na błonach śluzowych',
      'Nadwrażliwość na światło, pieczenie oczu',
      'Zmęczenie',
    ],
    atRisk: [
      'Weganie i osoby unikające nabiału',
      'Intensywnie trenujący (zwiększone zapotrzebowanie)',
      'Osoby na niskokalorycznej, monotonnej diecie',
    ],
    sources: [
      { food: 'Wątróbka', amount: '3 mg / 100 g' },
      { food: 'Migdały', amount: '1,1 mg / 100 g' },
      { food: 'Jaja', amount: '0,5 mg / 100 g' },
      { food: 'Pieczarki', amount: '0,4 mg / 100 g' },
      { food: 'Mleko / jogurt', amount: '0,2 mg / 100 g' },
    ],
    tip: 'Ryboflawina rozkłada się pod wpływem światła — dlatego mleko w przezroczystych butelkach traci ją szybciej. Nabiał, jaja i migdały to najpewniejsze źródła.',
    upperLimit: 'Rozpuszczalna w wodzie, nadmiar jest wydalany (barwi mocz na jaskrawożółto) — nie ustalono górnej granicy toksyczności.',
    references: [
      'EFSA (2017) — Dietary Reference Values for riboflavin',
      'Normy żywienia dla populacji Polski (NIZP-PZH, 2020)',
    ],
  },
  {
    id: 'witamina-b3',
    name: 'Witamina B3 (niacyna)',
    symbol: 'B3',
    category: 'witaminy',
    tagline: 'Metabolizm energetyczny i regeneracja',
    riskForActive: 'niskie',
    rda: { men: '16 mg', women: '14 mg' },
    unit: 'mg',
    whyActive:
      'Niacyna jest budulcem koenzymów NAD i NADP, kluczowych w setkach reakcji przemiany energii oraz w naprawie DNA i regeneracji komórek. Wspiera produkcję energii z makroskładników podczas wysiłku. Organizm potrafi ją częściowo wytwarzać z aminokwasu tryptofanu.',
    deficiencySigns: [
      'Zmęczenie i osłabienie',
      'Zmiany skórne (szorstkość, zaczerwienienie)',
      'Zaburzenia trawienia',
      'Rozdrażnienie, problemy z koncentracją',
    ],
    atRisk: [
      'Diety bardzo ubogie w białko',
      'Osoby nadużywające alkoholu',
    ],
    sources: [
      { food: 'Tuńczyk', amount: '18 mg / 100 g' },
      { food: 'Pierś z kurczaka', amount: '11 mg / 100 g' },
      { food: 'Wątróbka', amount: '15 mg / 100 g' },
      { food: 'Orzeszki ziemne', amount: '14 mg / 100 g' },
      { food: 'Łosoś', amount: '8 mg / 100 g' },
    ],
    tip: 'Dieta bogata w białko (mięso, ryby, strączki) zwykle w pełni pokrywa zapotrzebowanie na niacynę — także dzięki konwersji z tryptofanu.',
    upperLimit: 'Górna granica dla niacyny z suplementów to 35 mg/dobę. Wysokie dawki kwasu nikotynowego wywołują tzw. flush (zaczerwienienie i pieczenie skóry) i mogą obciążać wątrobę.',
    references: [
      'EFSA (2014) — Dietary Reference Values for niacin',
      'Normy żywienia dla populacji Polski (NIZP-PZH, 2020)',
    ],
  },
  {
    id: 'witamina-b5',
    name: 'Witamina B5 (kwas pantotenowy)',
    symbol: 'B5',
    category: 'witaminy',
    tagline: 'Składnik koenzymu A i przemiany energii',
    riskForActive: 'niskie',
    rda: { men: '5 mg (AI)', women: '5 mg (AI)' },
    unit: 'mg',
    whyActive:
      'Kwas pantotenowy jest składnikiem koenzymu A, niezbędnego do przemiany węglowodanów, tłuszczów i białek w energię oraz do syntezy hormonów i cholesterolu. Jest szeroko rozpowszechniony w żywności (nazwa pochodzi od greckiego „pantos” — wszędzie), dlatego niedobory są bardzo rzadkie.',
    deficiencySigns: [
      'Niedobór występuje wyjątkowo rzadko',
      'Zmęczenie, apatia (przy skrajnym niedoborze)',
      'Drętwienie i pieczenie stóp',
    ],
    atRisk: [
      'Osoby skrajnie niedożywione',
      'Osoby nadużywające alkoholu',
    ],
    sources: [
      { food: 'Wątróbka', amount: '7 mg / 100 g' },
      { food: 'Nasiona słonecznika', amount: '1,1 mg / 100 g' },
      { food: 'Awokado', amount: '1,4 mg / 100 g' },
      { food: 'Jaja', amount: '1,5 mg / 100 g' },
      { food: 'Pieczarki', amount: '1,5 mg / 100 g' },
    ],
    tip: 'Ze względu na powszechne występowanie w żywności suplementacja kwasu pantotenowego u zdrowych osób jest praktycznie zbędna — wystarczy zróżnicowana dieta.',
    upperLimit: 'Rozpuszczalny w wodzie — nie ustalono górnej granicy toksyczności. Bardzo wysokie dawki mogą działać przeczyszczająco.',
    references: [
      'EFSA (2014) — Dietary Reference Values for pantothenic acid',
      'Normy żywienia dla populacji Polski (NIZP-PZH, 2020)',
    ],
  },
  {
    id: 'witamina-b6',
    name: 'Witamina B6 (pirydoksyna)',
    symbol: 'B6',
    category: 'witaminy',
    tagline: 'Metabolizm białek i produkcja krwi',
    riskForActive: 'umiarkowane',
    rda: { men: '1,3 mg', women: '1,3 mg' },
    unit: 'mg',
    whyActive:
      'Witamina B6 jest kluczowa w metabolizmie aminokwasów — im więcej białka w diecie (a osoby budujące mięśnie jedzą go dużo), tym większe zapotrzebowanie na B6. Uczestniczy też w produkcji hemoglobiny, neuroprzekaźników oraz w uwalnianiu glukozy z glikogenu podczas wysiłku.',
    deficiencySigns: [
      'Zmęczenie i osłabienie',
      'Anemia',
      'Drażliwość, obniżony nastrój',
      'Zmiany skórne, pęknięcia w kącikach ust',
    ],
    atRisk: [
      'Osoby na diecie bardzo wysokobiałkowej',
      'Osoby na niskokalorycznej, monotonnej diecie',
    ],
    sources: [
      { food: 'Łosoś', amount: '0,9 mg / 100 g' },
      { food: 'Pierś z kurczaka', amount: '0,6 mg / 100 g' },
      { food: 'Ciecierzyca', amount: '0,5 mg / 100 g' },
      { food: 'Banan', amount: '0,4 mg / 100 g' },
      { food: 'Ziemniaki', amount: '0,3 mg / 100 g' },
    ],
    tip: 'Jeśli jesz dużo białka na budowę mięśni, zadbaj też o źródła B6 (ryby, drób, banany, ziemniaki) — zapotrzebowanie rośnie razem z podażą białka.',
    upperLimit: 'Górna granica z suplementów to 25 mg/dobę (wg EFSA). Długotrwałe megadawki (setki mg) mogą uszkadzać nerwy obwodowe — objaw paradoksalnie podobny do niedoboru.',
    references: [
      'EFSA (2016) — Dietary Reference Values for vitamin B6',
      'Normy żywienia dla populacji Polski (NIZP-PZH, 2020)',
    ],
  },
  {
    id: 'witamina-b7',
    name: 'Witamina B7 (biotyna)',
    symbol: 'B7',
    category: 'witaminy',
    tagline: 'Metabolizm makroskładników, skóra i włosy',
    riskForActive: 'niskie',
    rda: { men: '30 µg (AI)', women: '30 µg (AI)' },
    unit: 'µg',
    whyActive:
      'Biotyna jest koenzymem w przemianie węglowodanów, tłuszczów i białek oraz w syntezie glukozy i kwasów tłuszczowych. Wspiera zdrowie skóry, włosów i paznokci. Jest częściowo wytwarzana przez bakterie jelitowe, a niedobór u zdrowych osób jest bardzo rzadki.',
    deficiencySigns: [
      'Wypadanie włosów, łamliwość paznokci',
      'Wysypki i zmiany skórne',
      'Zmęczenie, apatia',
      'Niedobór występuje rzadko',
    ],
    atRisk: [
      'Osoby jedzące dużo surowych białek jaj (awidyna wiąże biotynę)',
      'Osoby po długiej antybiotykoterapii',
    ],
    sources: [
      { food: 'Wątróbka', amount: '100 µg / 100 g' },
      { food: 'Żółtko jaja', amount: '50 µg / 100 g' },
      { food: 'Orzechy (migdały, włoskie)', amount: '35 µg / 100 g' },
      { food: 'Soja', amount: '60 µg / 100 g' },
      { food: 'Pieczarki', amount: '16 µg / 100 g' },
    ],
    tip: 'Surowe białko jaja zawiera awidynę, która blokuje wchłanianie biotyny — gotowanie ją unieczynnia. Modne suplementy „na włosy i paznokcie” z megadawkami biotyny nie mają uzasadnienia u osób bez niedoboru.',
    upperLimit: 'Rozpuszczalna w wodzie — nie ustalono górnej granicy toksyczności. Uwaga: wysokie dawki biotyny mogą zaburzać wyniki niektórych badań laboratoryjnych (np. tarczycy) — poinformuj o niej lekarza.',
    references: [
      'EFSA (2014) — Dietary Reference Values for biotin',
      'Normy żywienia dla populacji Polski (NIZP-PZH, 2020)',
    ],
  },
  {
    id: 'fosfor',
    name: 'Fosfor',
    symbol: 'P',
    category: 'mineraly',
    tagline: 'Kości, zęby i produkcja energii (ATP)',
    riskForActive: 'niskie',
    rda: { men: '700 mg', women: '700 mg' },
    unit: 'mg',
    whyActive:
      'Fosfor razem z wapniem buduje kości i zęby, jest składnikiem ATP (nośnika energii w mięśniach) oraz błon komórkowych i DNA. Kluczowa jest równowaga wapniowo-fosforanowa — problemem w diecie zachodniej jest raczej nadmiar fosforu (przetworzona żywność, cola) niż jego niedobór.',
    deficiencySigns: [
      'Niedobór u zdrowych osób jest bardzo rzadki',
      'Osłabienie mięśni i kości (przy skrajnym niedoborze)',
      'Zmęczenie, bóle kostne',
    ],
    atRisk: [
      'Osoby skrajnie niedożywione',
      'Osoby nadużywające alkoholu',
    ],
    sources: [
      { food: 'Ser żółty', amount: '600 mg / 100 g' },
      { food: 'Nasiona dyni', amount: '1200 mg / 100 g' },
      { food: 'Ryby', amount: '250 mg / 100 g' },
      { food: 'Mięso', amount: '200 mg / 100 g' },
      { food: 'Rośliny strączkowe', amount: '350 mg / 100 g' },
    ],
    tip: 'Nie skupiaj się na dostarczaniu fosforu — jest go pod dostatkiem w białkowej diecie. Warto raczej ograniczać jego nadmiar z przetworzonej żywności (fosforany jako dodatki E), który przy dużej podaży zaburza gospodarkę wapniową.',
    upperLimit: 'Nadmiar fosforu (zwłaszcza z dodatków do żywności i napojów typu cola) przy niskiej podaży wapnia może niekorzystnie wpływać na kości i nerki.',
    references: [
      'EFSA (2015) — Dietary Reference Values for phosphorus',
      'Normy żywienia dla populacji Polski (NIZP-PZH, 2020)',
    ],
  },
  {
    id: 'cholina',
    name: 'Cholina',
    symbol: 'Ch',
    category: 'witaminy',
    tagline: 'Wątroba, praca mięśni i mózgu',
    riskForActive: 'umiarkowane',
    rda: { men: '550 mg (AI)', women: '425 mg (AI)' },
    unit: 'mg',
    whyActive:
      'Cholina (substancja witaminopodobna) jest niezbędna do metabolizmu tłuszczów w wątrobie, budowy błon komórkowych oraz produkcji acetylocholiny — neuroprzekaźnika odpowiadającego m.in. za skurcz mięśni i pamięć. Organizm produkuje jej niewiele, więc liczy się podaż z diety; głównymi źródłami są produkty zwierzęce.',
    deficiencySigns: [
      'Stłuszczenie wątroby',
      'Zmęczenie i osłabienie mięśni',
      'Problemy z pamięcią i koncentracją',
    ],
    atRisk: [
      'Weganie i wegetarianie (niska podaż z diety roślinnej)',
      'Osoby jedzące mało jaj i mięsa',
    ],
    sources: [
      { food: 'Żółtko jaja', amount: '680 mg / 100 g' },
      { food: 'Wątróbka wołowa', amount: '420 mg / 100 g' },
      { food: 'Mięso i drób', amount: '80 mg / 100 g' },
      { food: 'Ryby (dorsz, łosoś)', amount: '85 mg / 100 g' },
      { food: 'Soja', amount: '120 mg / 100 g' },
    ],
    tip: 'Jaja to jedno z najlepszych i najtańszych źródeł choliny — dwa jaja pokrywają znaczną część dziennego zapotrzebowania. Weganie powinni sięgać po soję, brokuły i orzeszki ziemne lub rozważyć suplement.',
    upperLimit: 'Górna granica to 3500 mg/dobę. Nadmiar może powodować „rybi” zapach ciała, nudności i spadek ciśnienia.',
    references: [
      'EFSA (2016) — Dietary Reference Values for choline',
      'Normy żywienia dla populacji Polski (NIZP-PZH, 2020)',
    ],
  },
  {
    id: 'mangan',
    name: 'Mangan',
    symbol: 'Mn',
    category: 'mineraly',
    tagline: 'Enzymy antyoksydacyjne i kości',
    riskForActive: 'niskie',
    rda: { men: '2,3 mg (AI)', women: '1,8 mg (AI)' },
    unit: 'mg',
    whyActive:
      'Mangan jest składnikiem enzymu antyoksydacyjnego (dysmutazy ponadtlenkowej, SOD) chroniącego mitochondria przed stresem oksydacyjnym z wysiłku, a także uczestniczy w tworzeniu kości i tkanki łącznej oraz w metabolizmie węglowodanów. Niedobór u ludzi jest bardzo rzadki.',
    deficiencySigns: [
      'Niedobór u ludzi występuje wyjątkowo rzadko',
      'Osłabienie kości i tkanki łącznej (teoretycznie)',
    ],
    atRisk: [
      'Osoby na skrajnie ubogiej, monotonnej diecie',
    ],
    sources: [
      { food: 'Orzechy laskowe', amount: '6 mg / 100 g' },
      { food: 'Płatki owsiane', amount: '4 mg / 100 g' },
      { food: 'Kasza gryczana', amount: '1,3 mg / 100 g' },
      { food: 'Herbata (napar)', amount: '0,5 mg / 100 ml' },
      { food: 'Szpinak', amount: '0,9 mg / 100 g' },
    ],
    tip: 'Pełnoziarniste zboża, orzechy i warzywa liściaste z nadwyżką pokrywają zapotrzebowanie na mangan — suplementacja jest zbędna i niezalecana bez wskazań.',
    upperLimit: 'Górna granica to ok. 11 mg/dobę. Nadmiar (głównie z zanieczyszczonej wody lub suplementów) może być neurotoksyczny.',
    references: [
      'EFSA (2013) — Dietary Reference Values for manganese',
      'Normy żywienia dla populacji Polski (NIZP-PZH, 2020)',
    ],
  },
  {
    id: 'chrom',
    name: 'Chrom',
    symbol: 'Cr',
    category: 'mineraly',
    tagline: 'Wsparcie gospodarki glukozowej (słabe dowody)',
    riskForActive: 'niskie',
    rda: { men: '35 µg (AI)', women: '25 µg (AI)' },
    unit: 'µg',
    whyActive:
      'Chrom (w formie trójwartościowej) potencjalizuje działanie insuliny i bierze udział w metabolizmie glukozy i tłuszczów. Bywa reklamowany jako suplement „na spalanie tłuszczu” i kontrolę apetytu, jednak dowody naukowe na realne korzyści z suplementacji u osób bez niedoboru są słabe i niejednoznaczne — warto podchodzić do tych obietnic sceptycznie.',
    deficiencySigns: [
      'Klinicznie istotny niedobór jest bardzo rzadki',
      'Teoretycznie: gorsza tolerancja glukozy',
    ],
    atRisk: [
      'Osoby na diecie opartej o wysoko przetworzone produkty',
    ],
    sources: [
      { food: 'Brokuł', amount: '11 µg / 100 g' },
      { food: 'Pełnoziarniste produkty', amount: '5–10 µg / 100 g' },
      { food: 'Mięso', amount: '2 µg / 100 g' },
      { food: 'Drożdże piwne', amount: 'wysoko' },
      { food: 'Orzechy', amount: '3 µg / 100 g' },
    ],
    tip: 'Zapotrzebowanie łatwo pokryć zwykłą, urozmaiconą dietą. Popularne spalacze tłuszczu z chromem („picolinian chromu”) nie mają mocnego uzasadnienia naukowego — nie licz na spektakularne efekty.',
    upperLimit: 'Nie ustalono jednoznacznej górnej granicy dla chromu z żywności. Bardzo wysokie dawki suplementów (picolinian) budzą pewne wątpliwości co do bezpieczeństwa.',
    references: [
      'EFSA (2014) — Scientific Opinion on chromium',
      'Normy żywienia dla populacji Polski (NIZP-PZH, 2020)',
    ],
  },
]

// Grupy podwyższonego ryzyka niedoboru — do filtrowania składników.
export const RISK_GROUPS = [
  { id: 'weganie', label: 'Weganie i wegetarianie' },
  { id: 'kobiety', label: 'Kobiety' },
  { id: 'sportowcy', label: 'Intensywnie trenujący' },
  { id: 'redukcja', label: 'Osoby na redukcji' },
]

// Przypisanie składników do grup, dla których ryzyko niedoboru jest podwyższone.
export const NUTRIENT_GROUPS = {
  'zelazo': ['kobiety', 'weganie', 'sportowcy', 'redukcja'],
  'witamina-d': ['sportowcy'],
  'magnez': ['sportowcy', 'redukcja'],
  'wapn': ['weganie', 'kobiety', 'redukcja'],
  'cynk': ['weganie', 'sportowcy'],
  'witamina-b12': ['weganie'],
  'sod': ['sportowcy'],
  'potas': ['sportowcy'],
  'witamina-c': [],
  'kwas-foliowy': ['kobiety'],
  'jod': ['weganie'],
  'witamina-e': [],
  'witamina-a': [],
  'selen': [],
  'miedz': [],
  'omega-3': ['weganie', 'sportowcy'],
  'witamina-k': [],
  'witamina-b1': ['sportowcy', 'redukcja'],
  'witamina-b2': ['weganie', 'sportowcy'],
  'witamina-b3': [],
  'witamina-b5': [],
  'witamina-b6': ['sportowcy'],
  'witamina-b7': [],
  'fosfor': [],
  'cholina': ['weganie', 'sportowcy'],
  'mangan': [],
  'chrom': [],
}

// Interakcje między składnikami (synergie i antagonizmy). Nie każdy składnik je ma.
export const INTERACTIONS = {
  'zelazo': [
    { kind: 'synergia', label: 'Witamina C', note: 'Znacząco zwiększa wchłanianie żelaza roślinnego (niehemowego).' },
    { kind: 'antagonizm', label: 'Wapń', note: 'Duża porcja wapnia w tym samym posiłku hamuje wchłanianie żelaza — rozdziel je w czasie.' },
    { kind: 'antagonizm', label: 'Cynk', note: 'Wysokie dawki cynku i żelaza konkurują o wchłanianie.' },
  ],
  'wapn': [
    { kind: 'synergia', label: 'Witamina D', note: 'Jest niezbędna do wchłaniania wapnia z jelit.' },
    { kind: 'synergia', label: 'Witamina K', note: 'Kieruje wapń do kości (aktywacja osteokalcyny), a nie do naczyń.' },
    { kind: 'antagonizm', label: 'Żelazo', note: 'Konkuruje z żelazem o wchłanianie — nie łącz suplementów w jednym posiłku.' },
  ],
  'witamina-d': [
    { kind: 'synergia', label: 'Wapń', note: 'Witamina D umożliwia efektywne wchłanianie i wykorzystanie wapnia.' },
    { kind: 'synergia', label: 'Magnez', note: 'Jest kofaktorem potrzebnym do aktywacji witaminy D w organizmie.' },
    { kind: 'synergia', label: 'Witamina K', note: 'Wspólnie wspierają prawidłową mineralizację kości.' },
  ],
  'magnez': [
    { kind: 'synergia', label: 'Witamina D', note: 'Magnez uczestniczy w aktywacji witaminy D — niedobór jednego pogarsza działanie drugiego.' },
  ],
  'cynk': [
    { kind: 'antagonizm', label: 'Miedź', note: 'Długotrwałe wysokie dawki cynku obniżają poziom miedzi w organizmie.' },
    { kind: 'antagonizm', label: 'Żelazo', note: 'Przy wysokich dawkach konkurują o wchłanianie.' },
  ],
  'miedz': [
    { kind: 'synergia', label: 'Żelazo', note: 'Miedź jest potrzebna do prawidłowego wykorzystania żelaza i produkcji krwinek.' },
    { kind: 'antagonizm', label: 'Cynk', note: 'Nadmiar cynku z suplementów blokuje wchłanianie miedzi.' },
  ],
  'witamina-c': [
    { kind: 'synergia', label: 'Żelazo', note: 'Wyraźnie zwiększa wchłanianie żelaza roślinnego z posiłku.' },
    { kind: 'synergia', label: 'Witamina E', note: 'Odtwarza aktywną formę witaminy E — współpraca antyoksydacyjna.' },
  ],
  'witamina-e': [
    { kind: 'synergia', label: 'Witamina C', note: 'Regeneruje utlenioną witaminę E po zneutralizowaniu wolnego rodnika.' },
  ],
  'witamina-a': [
    { kind: 'synergia', label: 'Tłuszcz i cynk', note: 'Tłuszcz w posiłku poprawia wchłanianie, a cynk wspiera transport witaminy A.' },
  ],
  'witamina-k': [
    { kind: 'synergia', label: 'Witamina D', note: 'Razem regulują gospodarkę wapniową i zdrowie kości.' },
    { kind: 'synergia', label: 'Wapń', note: 'Kieruje wapń do kości zamiast do ścian naczyń.' },
  ],
  'kwas-foliowy': [
    { kind: 'synergia', label: 'Witamina B12', note: 'Współdziałają w produkcji krwi; nadmiar folianów może maskować niedobór B12.' },
  ],
  'witamina-b12': [
    { kind: 'synergia', label: 'Foliany (B9)', note: 'Działają wspólnie przy tworzeniu czerwonych krwinek.' },
  ],
  'fosfor': [
    { kind: 'antagonizm', label: 'Wapń', note: 'Nadmiar fosforu (np. z napojów typu cola) zaburza równowagę wapniowo-fosforanową i szkodzi kościom.' },
  ],
  'omega-3': [
    { kind: 'antagonizm', label: 'Omega-6', note: 'Nadmiar omega-6 (oleje roślinne) względem omega-3 nasila procesy zapalne — liczy się proporcja.' },
  ],
}
