export const QUIZZES = [
  {
    id: 'basics',
    title: 'Podstawy dietetyki sportowej',
    description: 'Bilans energetyczny, BMR, TDEE i fundamenty żywienia sportowców',
    icon: 'BasicIcon',
    color: 'from-green-500 to-emerald-600',
    questions: [
      {
        question: 'Ile kalorii dostarcza 1 gram białka?',
        options: ['2 kcal', '4 kcal', '7 kcal', '9 kcal'],
        correct: 1,
        explanation: 'Białko i węglowodany dostarczają 4 kcal/g, tłuszcze 9 kcal/g, alkohol 7 kcal/g (współczynniki Atwatера). To podstawa do obliczania kaloryczności diety.',
      },
      {
        question: 'Ile białka dziennie zaleca ISSN dla sportowców siłowych dążących do hipertrofii?',
        options: ['0.8 g/kg mc', '1.2–1.4 g/kg mc', '1.6–2.2 g/kg mc', '3.5–4.0 g/kg mc'],
        correct: 2,
        explanation: 'ISSN Position Stand (2017) zaleca 1.6–2.2 g/kg mc/dzień dla maksymalizacji hipertrofii. Metaanaliza Morton i wsp. (2018, BJSM) potwierdza, że powyżej ~2.2 g/kg efekty są minimalne.',
      },
      {
        question: 'Co opisuje wskaźnik PAL (Physical Activity Level)?',
        options: [
          'Poziom kwasu mlekowego we krwi',
          'Współczynnik aktywności fizycznej mnożony przez BMR = TDEE',
          'Puls maksymalny osiągany na treningu',
          'Procentową zawartość tłuszczu w ciele',
        ],
        correct: 1,
        explanation: 'PAL to współczynnik aktywności fizycznej (1.2–1.9+). TDEE = BMR × PAL. Osoba siedząca ma PAL ≈ 1.2, sportowiec wyczynowy ≈ 1.9–2.4.',
      },
      {
        question: 'Który wzór do obliczania BMR jest rekomendowany przez Academy of Nutrition and Dietetics jako najdokładniejszy?',
        options: ['Harrisa-Benedicta (1919)', 'Mifflina-St Jeora (1990)', 'Cunninghama', 'Katch-McArdle'],
        correct: 1,
        explanation: 'Wzór Mifflina-St Jeora (1990) jest rekomendowany przez AND jako najdokładniejszy dla ogólnej populacji (dokładność ±10%). Wzór Cunninghama jest dokładniejszy dla sportowców ze znaną beztłuszczową masą ciała.',
      },
      {
        question: 'Jaki jest optymalny deficyt kaloryczny dla sportowca chcącego redukować tkankę tłuszczową przy zachowaniu masy mięśniowej?',
        options: ['100–200 kcal/dzień', '300–500 kcal/dzień', '1000–1500 kcal/dzień', '2000+ kcal/dzień'],
        correct: 1,
        explanation: 'Deficyt 300–500 kcal/dzień (ok. 0.5% masy ciała tygodniowo) minimalizuje utratę masy mięśniowej u sportowców. Większy deficyt zwiększa ryzyko katabolizmu i pogarsza regenerację (Helms 2014, ISSN).',
      },
      {
        question: 'Co to jest TEF (Thermic Effect of Food)?',
        options: [
          'Temperatura, w której gotuje się posiłek',
          'Energia wydatkowana na trawienie, wchłanianie i metabolizm pokarmu (~10% TDEE)',
          'Efekt cieplny ćwiczeń fizycznych',
          'Wskaźnik termiczny suplementów',
        ],
        correct: 1,
        explanation: 'TEF (efekt termiczny pożywienia) stanowi ~10% TDEE. Białko ma najwyższy TEF (20–30%), węglowodany 5–10%, tłuszcze 0–3%. Dlatego diety wysokobiałkowe mają przewagę termiczną.',
      },
      {
        question: 'Jakie jest główne źródło energii podczas intensywnego treningu siłowego (>80% VO2max)?',
        options: [
          'Kwasy tłuszczowe z tkanki tłuszczowej',
          'Glikogen mięśniowy (węglowodany)',
          'Białko mięśniowe',
          'Ketony',
        ],
        correct: 1,
        explanation: 'Przy wysokiej intensywności (>80% VO2max) glikogen mięśniowy jest dominującym substratorem energetycznym. System ATP-PCr (~10 s) i glikoliza beztlenowa (do ~2 min) są kluczowe dla pracy siłowej.',
      },
      {
        question: 'Co to jest Energy Availability (EA) i jakie minimum zapewnia zdrowie fizjologiczne?',
        options: [
          'Dostępność pokarmu w sklepie – min. 1000 kcal/dzień',
          '(Spożycie energii – koszt treningu) / FFM – minimum ≥45 kcal/kg FFM/dzień',
          'Kaloryczność diety bez tłuszczu – min. 800 kcal/dzień',
          'Całkowita energia z węglowodanów – min. 200 g/dzień',
        ],
        correct: 1,
        explanation: 'EA = (spożycie kcal − koszt treningu) ÷ beztłuszczowa masa ciała (FFM). EA <30 kcal/kg FFM/dzień wywołuje zaburzenia hormonalne, kostne i immunologiczne (RED-S). Optimum to ≥45 kcal/kg FFM/dzień (Loucks 2003).',
      },
      {
        question: 'Główne elektrolity tracone z potem podczas wysiłku to:',
        options: [
          'Wapń i magnez',
          'Sód i chlor (40–60 mmol/L potu)',
          'Potas i fosfor',
          'Żelazo i cynk',
        ],
        correct: 1,
        explanation: 'Pot zawiera głównie sód (20–80 mmol/L) i chlor. Utrata 1 L potu to 1–2.5 g sodu. Hiponatremia wysiłkowa (niedobór sodu) jest poważnym ryzykiem podczas długotrwałego wysiłku i nadmiernej podaży wody.',
      },
      {
        question: 'Jaki jest mechanizm działania „dodatniego bilansu azotowego" w kontekście hipertrofii mięśniowej?',
        options: [
          'Azot z białka odkłada się bezpośrednio w mięśniach jako masa',
          'Synteza białek mięśniowych (MPS) przewyższa ich rozpad (MPB) – konieczny warunek hipertrofii',
          'Azot blokuje kortyzol i tym samym zapobiega katabolizmowi',
          'Zwiększona retencja azotu oznacza wyższy poziom kreatyny',
        ],
        correct: 1,
        explanation: 'Hipertrofia zachodzi gdy MPS > MPB (dodatni bilans azotowy / białkowy). Osiąga się go przez: odpowiednie spożycie białka (~1.6–2.2 g/kg), trening oporowy i surplus kaloryczny. Bilans azotowy mierzy się przez 24h zbiórki moczu (N spożyty – N wydalony).',
      },
    ],
  },
  {
    id: 'macros',
    title: 'Makroskładniki dla sportowców',
    description: 'Białko, węglowodany i tłuszcze – dawkowanie, timing i strategie żywieniowe',
    icon: 'MacrosIcon',
    color: 'from-blue-500 to-cyan-600',
    questions: [
      {
        question: 'Które aminokwasy wchodzą w skład BCAA?',
        options: [
          'Leucyna, izoleucyna, walina',
          'Glicyna, alanina, prolina',
          'Metionina, cysteina, tryptofan',
          'Glutamina, arginina, lizyna',
        ],
        correct: 0,
        explanation: 'BCAA (Branched-Chain Amino Acids) to leucyna, izoleucyna i walina – aminokwasy egzogenne o rozgałęzionym łańcuchu. Leucyna jest kluczowym aktywatorem syntezy białek mięśniowych przez szlak mTORC1.',
      },
      {
        question: 'Kiedy najlepiej spożyć posiłek bogaty w węglowodany przed treningiem siłowym?',
        options: ['10–15 minut przed', '1–3 godziny przed', '5–6 godzin przed', 'Węglowodany nie są potrzebne przed treningiem siłowym'],
        correct: 1,
        explanation: 'Posiłek mieszany 1–3h przed treningiem pozwala na optymalną dostępność glikogenu i glukozy we krwi. Bezpośrednio przed treningiem można spożyć mały przekąskę (banan, żel) – nie pełny posiłek (ryzyko dyskomfortu GI).',
      },
      {
        question: 'Jaka dawka leucyny optymalnie stymuluje syntezę białek mięśniowych (MPS) na porcję?',
        options: ['0.3 g', '0.7–1.0 g', '2–3 g', '8–10 g'],
        correct: 2,
        explanation: '„Próg leucynowy" wynosi ok. 2–3 g leucyny na porcję (Norton & Layman 2006). Odpowiada to ~20–30 g kompletnego białka (whey/mięso). Poniżej progu synteza białek jest suboptymalna.',
      },
      {
        question: 'Ile gramów węglowodanów na kg mc dziennie zaleca się sportowcom wytrzymałościowym w okresie intensywnych treningów?',
        options: ['1–2 g/kg', '3–5 g/kg', '6–10 g/kg', '12–15 g/kg'],
        correct: 2,
        explanation: 'Burke i wsp. (ISSN 2011) zalecają 6–10 g węglowodanów/kg mc/dzień dla sportowców wytrzymałościowych w intensywnym treningu. W ultra-wytrzymałości nawet 10–12 g/kg. W dniach bez treningu wystarczy 3–5 g/kg.',
      },
      {
        question: 'Minimalne spożycie tłuszczów gwarantujące zdrowie hormonalne u sportowca to:',
        options: ['0.2–0.3 g/kg mc', '0.5–1.0 g/kg mc', '2.0–2.5 g/kg mc', 'Tłuszcze nie są potrzebne sportowcom'],
        correct: 1,
        explanation: 'Spożycie tłuszczów <0.5 g/kg mc prowadzi do: ↓testosteronu, ↓estrogenu, niedoborów witamin ADEK i zaburzeń funkcji komórek. ISSN i ACSM zalecają min. 0.5–1.0 g/kg mc (20–35% kalorii).',
      },
      {
        question: 'Co to jest ładowanie glikogenu (carbohydrate loading)?',
        options: [
          'Jedzenie dużo cukru tydzień przed zawodami bez modyfikacji treningu',
          'Protokół: ↓treningu + ↑węglowodanów (8–12 g/kg przez 1–3 dni) przed startem, zwiększający glikogen o 20–40%',
          'Suplementacja glukozą w trakcie zawodów',
          'Unikanie węglowodanów 48h przed startem',
        ],
        correct: 1,
        explanation: 'Klasyczny protokół ładowania (Bergström 1967, zmodyfikowany Burke 2017): 3 dni ↑węglowodanów (10–12 g/kg) + tapering treningowy. Zwiększa glikogen o 20–40%, co poprawia wyniki w dyscyplinach >90 min. Bez fazy deplecji nie traci skuteczności.',
      },
      {
        question: 'Białko serwatkowe (whey) jest preferowane po treningu, ponieważ:',
        options: [
          'Jest najtańsze na rynku',
          'Trawi się szybko (~10 g/h), zawiera ~11% leucyny i szybko podnosi poziom aminokwasów w krwi',
          'Nie zawiera laktozy',
          'Lepiej smakuje niż kazeina',
        ],
        correct: 1,
        explanation: 'Whey: szybkie trawienie (szczyt aminoacydemii ~60 min), wysoka zawartość leucyny (~11%), pełny profil EAA. Kazeina trawi się 3–6h (białko „nocne"). Oba zwiększają MPS, whey jest jednak skuteczniejszy bezpośrednio po treningu (Tang 2009, Phillips 2012).',
      },
      {
        question: 'Co to jest strategia „Train Low, Compete High" w periodyzacji węglowodanów?',
        options: [
          'Trening na niskich pulsy, start na wysokich',
          'Wykonywanie części treningów przy niskim glikogenie → adaptacje metaboliczne, start na pełnych zapasach glikogenu',
          'Unikanie węglowodanów cały rok poza dniem zawodów',
          'Dieta ketogeniczna przez 6 dni, ładowanie dzień przed startem',
        ],
        correct: 1,
        explanation: '„Train low" (część treningów z niskim glikogenem) indukuje: ↑enzymy oksydacji FA (HAD, CS), ↑mitochondriogenezę, ↑AMPK. Start na pełnym glikogenie zapewnia optymalną wydolność. Burke i wsp. (2020, BJSM) potwierdzają korzyści przy właściwej periodyzacji.',
      },
      {
        question: 'Jaką rolę pełni szlak mTORC1 w syntezie białek mięśniowych?',
        options: [
          'Hamuje syntezę białek i chroni przed przetrenowaniem',
          'Jest kluczowym aktywatorem MPS – stymulowany przez leucynę, insulinę i obciążenie mechaniczne',
          'Reguluje wyłącznie metabolizm tłuszczów',
          'Jest enzymem trawiennym w jelicie cienkim',
        ],
        correct: 1,
        explanation: 'mTORC1 (mechanistic target of rapamycin complex 1) aktywuje translację mRNA → syntezę białek. Stymulatory: leucyna (bezpośrednio), insulina (pośrednio), obciążenie mechaniczne. Inhibitory: deficyt energii, rapamycyna, AMPK (aktywowany przy wyczerpaniu glikogenu).',
      },
      {
        question: 'Jaki jest optymalny rozkład porcji białka w ciągu dnia dla maksymalizacji MPS?',
        options: [
          '1 duży posiłek białkowy wieczorem (100 g białka naraz)',
          '2 porcje po 50 g rano i wieczorem',
          '3–5 równomiernych porcji po 20–40 g co 3–5 h w ciągu dnia',
          'Ciągłe sączenie białka przez cały dzień',
        ],
        correct: 2,
        explanation: 'Metaanaliza Areta i wsp. (2013, J Physiol) wykazała, że 4 porcje × 20 g co 3h dają wyższy MPS niż 2×40 g lub 8×10 g. Optymalnie 3–5 porcji po 20–40 g (w zależności od masy ciała) równomiernie w ciągu dnia, w tym przed snem (40 g kazeiny).',
      },
    ],
  },
  {
    id: 'supplementation',
    title: 'Suplementacja sportowa',
    description: 'Kreatyna, kofeina, beta-alanina i inne – co działa, co nie działa i dlaczego',
    icon: 'SupplIcon',
    color: 'from-purple-500 to-pink-600',
    questions: [
      {
        question: 'Kreatyna monowodzian poprawia wydolność głównie przez:',
        options: [
          'Zwiększenie poziomu testosteronu',
          'Zwiększenie zapasów fosfokreatyny (PCr) w mięśniach o ~20%',
          'Przyspieszenie metabolizmu tłuszczów',
          'Działanie jako elektrolit podczas wysiłku',
        ],
        correct: 1,
        explanation: 'Kreatyna ↑PCr o ~20%, co przedłuża dostępność ATP podczas wysiłków krótkich (ATP-PCr system, <10 s) i przyspiesza resyntezę PCr między seriami. ISSN (2017): najlepiej przebadany suplement ergeniczny, kategoria dowodów A.',
      },
      {
        question: 'Jaka jest ergogeniczna dawka kofeiny przed treningiem?',
        options: ['0.5 mg/kg mc (1 łyk espresso)', '3–6 mg/kg mc, 45–60 min przed', '10–15 mg/kg mc', '50 mg/kg mc'],
        correct: 1,
        explanation: 'Metaanalizy (Grgic 2018, BJSM; Pickering 2019) wykazują optymalną dawkę 3–6 mg/kg mc spożytą 45–60 min przed wysiłkiem. Poprawia wytrzymałość, siłę, koncentrację i percepcję wysiłku przez antagonizm receptorów adenozynowych.',
      },
      {
        question: 'Beta-alanina działa jako prekursor karnozyny, która:',
        options: [
          'Dostarcza energii do skurczu mięśni',
          'Buforuje jony H+ (protony) w mięśniach, opóźniając zakwaszenie przy intensywnym wysiłku',
          'Zwiększa poziom testosteronu',
          'Przyspiesza transport tlenu do mięśni',
        ],
        correct: 1,
        explanation: 'Karnozyna (β-alanina + histydyna) buforuje H+ powstające podczas intensywnej glikolizy. Suplementacja 3.2–6.4 g/dzień przez 4+ tyg. ↑karnozyna o 40–80%. Skuteczna głównie w wysiłkach 1–10 min (ISSN Position Stand 2015). Efekt uboczny: parestezje (mrowienie skóry).',
      },
      {
        question: 'Protokół ładowania kreatyną to:',
        options: [
          '100 g jednorazowo przed treningiem',
          '20 g/dzień (4×5 g) przez 5–7 dni, następnie faza podtrzymania 3–5 g/dzień',
          '1 g/dzień przez 12 miesięcy',
          '10 g przed i 10 g po każdym treningu',
        ],
        correct: 1,
        explanation: 'Ładowanie: 4×5 g dziennie przez 5–7 dni → pełne nasycenie PCr. Podtrzymanie: 3–5 g/dzień. Alternatywnie: 3–5 g/dzień bez ładowania – efekt po ~4 tyg. (Hultman 1996). Spożycie z węglowodanami i białkiem ↑wychwyt kreatyny przez mięśnie.',
      },
      {
        question: 'Azotany z soku z buraków poprawiają wydolność wytrzymałościową poprzez:',
        options: [
          'Dostarczenie żelaza do syntezy hemoglobiny',
          'Redukcję do NO (tlenku azotu) → rozszerzenie naczyń → ↓kosztu tlenowego wysiłku o ~3–5%',
          'Działanie jako szybkie źródło węglowodanów',
          'Stymulację wydzielania erytropoetyny (EPO)',
        ],
        correct: 1,
        explanation: 'NO3− → NO2− (bakterie w ustach) → NO (w tkankach). NO rozszerza naczynia, ↓ciśnienie, ↓koszt O2 skurczu mięśniowego. Efekt: ↑wydolność submaksymalna o 3–5% (Lansley 2011, Jones 2014). Dawka: ~400 mg NO3− (300 ml soku z buraków), 2–3h przed startem.',
      },
      {
        question: 'Cytrulina jest lepsza niż arginina jako prekursor tlenku azotu (NO), ponieważ:',
        options: [
          'Zawiera więcej azotu cząsteczkowego',
          'Omija metabolizm first-pass w jelicie i wątrobie, osiągając wyższe stężenia argininy w osoczu',
          'Działa szybciej bo jest mniejszą cząsteczką',
          'Arginina jest aminokwasem egzogennym i nie wchłania się z diety',
        ],
        correct: 1,
        explanation: 'Arginina jest intensywnie metabolizowana przez arginazę jelitową i wątrobową (efekt first-pass). Cytrulina omija ten szlak i jest konwertowana do argininy w nerkach, osiągając 2× wyższe stężenia w osoczu niż suplementacja argininą (Schwedhelm 2008). Dawka: 6–8 g L-cytruliny lub 8–10 g cytruina malat.',
      },
      {
        question: 'HMB (β-hydroksy-β-metylomaślan) jest metabolitem jakiego aminokwasu?',
        options: ['Glutaminy', 'Leucyny (3–5% leucyny jest konwertowane do HMB)', 'Waliny', 'Lizyny'],
        correct: 1,
        explanation: 'HMB to metabolit leucyny (ok. 5% leucyny → HMB). Wykazuje działanie antykataboliczne (↓MPB przez ↓aktywacji ubikwityny-proteasomu i kaspaz). Skuteczny u osób starszych, detreniowanych i w stanach katabolicznych. Efekty u doświadczonych sportowców są słabsze (Wilson 2014, JISSN).',
      },
      {
        question: 'Ashwagandha (Withania somnifera, KSM-66®) u sportowców wykazuje w badaniach RCT:',
        options: [
          'Silne działanie anaboliczne porównywalne do sterydów anabolicznych',
          'Adaptogenne działanie: ↓kortyzolu, ↑testosteronu, ↑VO2max i siły maksymalnej',
          'Wyłącznie działanie sedatywne i nasenne bez wpływu na wydolność',
          'Brak jakichkolwiek efektów potwierdzonych w RCT',
        ],
        correct: 1,
        explanation: 'RCT: Wankhede (2015) – 600 mg KSM-66® przez 8 tyg.: ↑siła, ↑masa mięśniowa, ↓kortyzol vs placebo. Choudhary (2015): ↑VO2max o ~7%. Efekty umiarkowane ale powtarzalne. Mechanizm: witanolidy ↓aktywację NF-κB i oś HPA (stres kortyzol).',
      },
      {
        question: 'Wodorowęglan sodu (NaHCO₃, soda oczyszczona) stosowany przez sportowców działa przez:',
        options: [
          'Dostarczenie sodu i węgla jako źródła energii',
          'Buforowanie kwasicy metabolicznej: ↑pH krwi → ↑gradient H+ z mięśni → ↑pojemność buforowa',
          'Pobudzenie układu nerwowego podobne do kofeiny',
          'Zwiększenie syntezy kreatyny endogennej',
        ],
        correct: 1,
        explanation: 'NaHCO3 (0.2–0.3 g/kg, 60–90 min przed startem) ↑pH krwi z ~7.4 do ~7.5, tworząc dodatkowy bufor zewnątrzkomórkowy. Metaanalizy: ↑wydolność ~2% w wysiłkach 1–10 min (Carr 2011). Ryzyko: dyskomfort GI u ~50% osób – protokół podzielonych dawek minimalizuje problem.',
      },
      {
        question: 'Które suplementy mają kategorię dowodów naukowych Grade A (silne dowody, bezpieczne i skuteczne) według ISSN?',
        options: [
          'Glutamina, BCAA, Tribulus terrestris',
          'Kreatyna monowodzian, kofeina, beta-alanina, azotany, białko serwatkowe',
          'HMB, ZMA, ekstrakt z zielonej herbaty',
          'Arginina, CLA, glukozamina',
        ],
        correct: 1,
        explanation: 'ISSN Grade A (silne dowody skuteczności i bezpieczeństwa): kreatyna, kofeina, beta-alanina, azotany, białko, węglowodany, wodorowęglan sodu. Glutamina i BCAA mają słabsze dowody dla sportowców (Grade B/C). Tribulus terrestris nie ma potwierdzenia skuteczności (Grade D).',
      },
    ],
  },
  {
    id: 'advanced',
    title: 'Zaawansowana dietetyka sportowa',
    description: 'RED-S, periodyzacja żywienia, fizjologia wysiłku i adaptacje metaboliczne',
    icon: 'AdvancedIcon',
    color: 'from-amber-500 to-orange-600',
    questions: [
      {
        question: 'Co to jest RED-S (Relative Energy Deficiency in Sport)?',
        options: [
          'Rodzaj anemii z niedoboru żelaza specyficzny dla biegaczy',
          'Zespół niedoboru energii relatywnego: EA <30 kcal/kg FFM/dzień zaburza funkcje hormonalne, kostne, immunologiczne i metaboliczne',
          'Suplement diety stosowany przy redukcji masy ciała',
          'Protokół treningowy w deficycie kalorycznym',
        ],
        correct: 1,
        explanation: 'RED-S (Mountjoy 2014, BJSM) to rozszerzenie koncepcji „triady sportsmenki". Opisuje skutki chronicznego niedoboru energii u sportowców obu płci: ↓gęstość kości, ↓libido, ↓testosteron/estrogen, ↓odporność, ↑kontuzje. EA = (kcal spożyte − kcal trening) ÷ FFM.',
      },
      {
        question: 'Co mierzy RER (Respiratory Exchange Ratio = VCO₂/VO₂) podczas wysiłku?',
        options: [
          'Pojemność minutową płuc',
          'Stosunek utylizacji substratów: RER 0.7 = 100% tłuszcze, RER 1.0 = 100% węglowodany',
          'Poziom kwasu mlekowego we krwi',
          'Tętno maksymalne podczas wysiłku',
        ],
        correct: 1,
        explanation: 'RER odzwierciedla proporcję spalanych substratów. Podczas spoczynku RER ≈ 0.82–0.85 (mieszana oxidacja). Przy intensywności przekraczającej VT2 (próg wentylacyjny) RER może przekroczyć 1.0 (dodatkowy CO2 z buforowania HCO3−). FAT MAX (max. utlenianie FA) zwykle przy RER ≈ 0.85 (45–65% VO2max).',
      },
      {
        question: 'Co to jest „FAT MAX" i w jakiej intensywności występuje u wytrenowanych sportowców?',
        options: [
          'Maksymalna zawartość tłuszczu w diecie sportowca – 40% kalorii',
          'Intensywność wysiłku przy max. utlenianiu kwasów tłuszczowych – zwykle 45–65% VO2max (Zone 2)',
          'Punkt, po którym organizm zaczyna spalać wyłącznie mięśnie',
          'Dawka tłuszczu przed treningiem dla max. energii',
        ],
        correct: 1,
        explanation: 'FAT MAX (Achten & Jeukendrup 2004) to punkt na krzywej utleniania FA. U wytrenowanych sportowców przesuwa się wyżej (nawet 65% VO2max) dzięki ↑mitochondriom i enzymom (HAD, CS). Trening Zone 2 (3–4 ×/tydzień) jest kluczowy dla ↑FAT MAX i wydolności tlenowej.',
      },
      {
        question: 'Periodyzacja węglowodanów „train low" polega na:',
        options: [
          'Diecie ketogenicznej przez cały sezon',
          'Strategicznym wykonywaniu wybranych treningów przy niskim glikogenie → ↑ekspresja genów adaptacji metabolicznych (PGC-1α, AMPK, HAD)',
          'Unikaniu węglowodanów wyłącznie przed snem',
          'Spożywaniu wyłącznie fruktozy zamiast glukozy',
        ],
        correct: 1,
        explanation: '„Train low" aktywuje AMPK (niski ATP) → PGC-1α → mitochondriogeneza, ↑enzymy β-oksydacji, ↑VO2max. Burke i wsp. (2020): 3 tyg. „sleep low" (trening wieczorem bez węglowodanów, brak CH na noc) ↑spalanie tłuszczu, ale ryzyko ↓jakości treningu wysokointensywnego przy chronicznym stosowaniu.',
      },
      {
        question: 'Jak hipoksja wysokogórska wpływa na gospodarkę żelaza u sportowców?',
        options: [
          'Zmniejsza zapotrzebowanie na żelazo bo ↑efektywność hemoglobiny',
          'HIF-1α → ↑EPO → ↑erytropoeza → ↑zapotrzebowanie na Fe (do syntezy Hb) → ryzyko niedoboru',
          'Hipoksja nie wpływa na metabolizm żelaza',
          'Powoduje nadmiar żelaza przez ↑wchłaniania jelitowego',
        ],
        correct: 1,
        explanation: 'Hipoksja aktywuje HIF-1α → ↑EPO (szpik kostny) → ↑produkcja erytrocytów → ↑zapotrzebowanie na Fe do syntezy hemoglobiny. Sportowcy na zgrupowaniach wysokogórskich (>2000 m n.p.m.) często wymagają suplementacji Fe (100–200 mg elementarnego Fe/dzień). Monitorowanie ferrytyny (<35 µg/L = niedobór) jest kluczowe (Govus 2015, BJSM).',
      },
      {
        question: 'Osmolarność optymalnego napoju izotonicznego podczas wysiłku wynosi:',
        options: [
          '50–100 mOsm/L (silnie hipotoniczny)',
          '270–330 mOsm/L (izotoniczny – zbliżony do osocza)',
          '400–500 mOsm/L (lekko hipertoniczny)',
          '>800 mOsm/L (silnie hipertoniczny)',
        ],
        correct: 1,
        explanation: 'Napój izotoniczny (270–330 mOsm/L) jest optymalny: nie opóźnia opróżniania żołądka, efektywnie nawadnia. Hipotone (<270) wchłaniają się szybciej, ale dostarczają mniej elektrolitów. Hipetoniczne (>330) spowalniają opróżnianie żołądka i mogą powodować biegunkę przy wysiłku.',
      },
      {
        question: 'Anemia sportowca jest często wieloczynnikowa. Który zestaw przyczyn jest najczęstszy u biegaczy długodystansowych?',
        options: [
          'Wyłącznie niedobór żelaza w diecie wegetariańskiej',
          'Hemodylucja (↑objętość osocza) + hemoliza śródsłopowa + utrata Fe z potem i moczem + mikrokrwawienia GI',
          'Nadmiar witaminy C blokujący wchłanianie żelaza',
          'Zbyt duże spożycie białka ↓wchłanianie Fe',
        ],
        correct: 1,
        explanation: '„Sports anemia" jest wieloczynnikowa (Selby & Eichner 1986, Sports Med): 1) Hemodylucja – ↑objętość osocza przy hematokrycie w normie (pseudoanemia); 2) Hemoliza mechaniczna (footstrike) – rozbijanie erytrocytów podczas biegu; 3) Utrata Fe z potem (~0.1–0.4 mg/L); 4) Mikrokrwawienia GI (NLPZ, wibracje). Ferrytyna <35 µg/L + ↓MCV + ↓TSAT wskazują na prawdziwy niedobór.',
      },
      {
        question: 'Interleukina-6 (IL-6) wydzielana przez pracujące mięśnie (jako miokina) pełni funkcję:',
        options: [
          'Wyłącznie prozapalną – powoduje ból mięśni po treningu (DOMS)',
          'Sygnalizacyjną: ↑lipoliza, ↑glukoneogeneza, ↑wychwyt glukozy – efekt antymetaboliczny i adaptacyjny',
          'Wyłącznie immunosupresyjną – blokuje infekcje po treningu',
          'Budulca mięśni analogicznego do IGF-1',
        ],
        correct: 1,
        explanation: 'IL-6 jako miokina (Pedersen 2007, Nat Rev Endocrinol) działa paradoksalnie: wydzielana przez mięśnie podczas wysiłku (nie z makrofagów) ↑lipolizę w tkance tłuszczowej, ↑glukoneogenezę wątrobową i ↑wychwyt glukozy przez mięśnie. Kontrastuje z IL-6 prozapalną uwalnianą przy infekcjach/urazach.',
      },
      {
        question: 'Co to jest „gut training" (trening jelitowy) w dietetyce wytrzymałościowej?',
        options: [
          'Ćwiczenia mięśni brzucha dla lepszego trawienia',
          'Systematyczne spożywanie węglowodanów podczas treningów → ↑ekspresja transporterów SGLT1/GLUT5 → tolerancja 90 g CHO/h',
          'Probiotykoterapia w celu poprawy mikrobioty jelitowej',
          'Dieta eliminacyjna FODMAP przed zawodami',
        ],
        correct: 1,
        explanation: 'Jelit można „wytrenować" (Jeukendrup 2017, Sports Med): regularne spożywanie węglowodanów (żele, napoje) podczas długich biegów/jazdy ↑ekspresję transporterów SGLT1 (glukoza) i GLUT5 (fruktoza) w jelicie. Pozwala to wchłaniać 90 g CHO/h (glukoza+fruktoza 2:1) zamiast standardowych ~60 g/h. Kluczowe dla ultramaratonów i triathlonów.',
      },
      {
        question: 'Jaki jest mechanizm działania fosfokreatyny (PCr) w układzie energetycznym ATP-PCr?',
        options: [
          'PCr jest bezpośrednim źródłem energii dla skurczu mięśni (zamiast ATP)',
          'PCr oddaje grupę fosforanową ADP → natychmiastowa resynteza ATP przez kinazę kreatynową (CK)',
          'PCr jest transporterem tlenu do mitochondriów podobnie jak mioglobina',
          'PCr reguluje pH mięśni poprzez buforowanie jonów H+',
        ],
        correct: 1,
        explanation: 'Reakcja CK: PCr + ADP → Cr + ATP (ΔG° = −43 kJ/mol). Zasoby PCr wystarczają na ~6–10 s maksymalnego wysiłku. Suplementacja kreatyną ↑PCr o ~20%, co wydłuża czas do wyczerpania PCr i przyspiesza jego resyntezę (czas pół-życia resyntez PCr: ~30 s). Kluczowe dla sprintów, skoków i ciężkich serii siłowych.',
      },
    ],
  },
]
