export const QUIZZES = [
  {
    id: 'basics',
    title: 'Quiz z bloga FitPlan',
    description: 'Sprawdź czy pamiętasz najważniejsze informacje z naszych artykułów o białku, suplementach i mikroelementach',
    icon: 'BasicIcon',
    color: 'from-green-500 to-emerald-600',
    questions: [
      {
        question: 'Ile białka dziennie potrzebuje osoba trenująca siłowo, żeby budować mięśnie?',
        options: ['0,8 g na kg masy ciała', '1,6–2,2 g na kg masy ciała', '4–5 g na kg masy ciała', 'Ilość białka nie ma znaczenia'],
        correct: 1,
        explanation: 'Osoby trenujące siłowo potrzebują 1,6–2,2 g białka na każdy kg masy ciała dziennie. Standardowe zalecenia (0,8 g/kg) są dla osób nieaktywnych i dla sportowców to zdecydowanie za mało.',
      },
      {
        question: 'Jaka dawka kofeiny przed treningiem daje najlepsze efekty?',
        options: ['1 mg na kg masy ciała', '3–4 mg na kg masy ciała', '10 mg na kg masy ciała', 'Dawka nie ma znaczenia'],
        correct: 1,
        explanation: 'Optymalna dawka kofeiny to 3–4 mg na każdy kg masy ciała, spożyta 30–40 minut przed treningiem. Dla osoby ważącej 80 kg to 240–320 mg — czyli mniej więcej 2–3 kawy.',
      },
      {
        question: 'Sok z buraka poprawia wytrzymałość, bo zawiera:',
        options: ['Dużo żelaza, które dotlenia krew', 'Azotany, które rozszerzają naczynia krwionośne i ułatwiają pracę mięśni', 'Cukry dające szybką energię', 'Witaminę C poprawiającą odporność'],
        correct: 1,
        explanation: 'Burak zawiera naturalne azotany, które w organizmie zamieniają się w tlenek azotu. Tlenek azotu rozszerza naczynia krwionośne — mięśnie dostają więcej tlenu i pracują wydajniej przy tym samym wysiłku.',
      },
      {
        question: 'Beta-alanina — po ilu tygodniach regularnego przyjmowania zaczynasz czuć pierwsze efekty?',
        options: ['Po 1 dniu', 'Po 2–4 tygodniach', 'Po 6 miesiącach', 'Efekty czuje się od razu'],
        correct: 1,
        explanation: 'Beta-alanina działa kumulacyjnie — jej zapasy w mięśniach budują się z czasem. Pierwsze efekty (mniej zakwaszenia mięśni podczas intensywnych ćwiczeń) pojawiają się po 2 tygodniach, pełny efekt po 4 tygodniach codziennego przyjmowania.',
      },
      {
        question: 'Cynk w dawce 50 mg wpłynął w badaniach na:',
        options: ['Wzrost poziomu kortyzolu', 'Obniżenie poziomu kortyzolu (hormonu stresu)', 'Zwiększenie masy mięśniowej', 'Poprawę snu'],
        correct: 1,
        explanation: 'W badaniu Brandão-Neto i wsp. podanie 50 mg cynku spowodowało znaczące obniżenie kortyzolu w porównaniu z placebo. Cynk jest szczególnie ważny dla osób aktywnych fizycznie, bo trening zwiększa jego straty przez pot.',
      },
      {
        question: 'Jaka dawka cytruliny malat jest zalecana przed treningiem?',
        options: ['2 g', '5 g', '10 g', '20 g'],
        correct: 2,
        explanation: '10 g cytruliny malat (lub 5–6 g samej L-cytruliny) spożyte ok. godziny przed treningiem daje najlepsze efekty. Cytrulina poprawia przepływ krwi do mięśni, zmniejsza zmęczenie i poprawia "pompę mięśniową".',
      },
      {
        question: 'Magnez i potas są szczególnie ważne dla ćwiczących, bo:',
        options: [
          'Dostarczają energii podczas treningu',
          'Pomagają regulować kortyzol (hormon stresu) i wspierają regenerację po treningu',
          'Budują masę mięśniową',
          'Przyspieszają spalanie tłuszczu',
        ],
        correct: 1,
        explanation: 'Magnez i potas pomagają regulować poziom kortyzolu i wspierają regenerację. Osoby aktywne fizycznie tracą te minerały przez pot i są szczególnie narażone na ich niedobory, które mogą utrudniać regenerację i pogarszać jakość snu.',
      },
      {
        question: 'Ile białka na jeden posiłek optymalnie stymuluje budowę mięśni u młodej osoby?',
        options: ['5 g (np. łyżka jogurtu)', '0,3 g na kg masy ciała (ok. 20–30 g dla 80 kg osoby)', '100 g (duży stek)', 'Ilość białka w jednym posiłku nie ma znaczenia'],
        correct: 1,
        explanation: 'Optymalnie ok. 0,3 g białka na kg masy ciała na jeden posiłek. Dla osoby ważącej 80 kg to ok. 24 g białka — tyle znajdziesz w 3 jajkach, 100 g kurczaka lub porcji odżywki białkowej. Więcej białka naraz nie daje proporcjonalnie lepszych efektów.',
      },
      {
        question: 'Glicerol przed treningiem pomaga, bo:',
        options: [
          'Dostarcza szybkiej energii podobnie jak cukier',
          'Pomaga organizmowi zatrzymać więcej wody przed treningiem, dzięki czemu wolniej się odwadniasz',
          'Zwiększa poziom testosteronu',
          'Przyspiesza spalanie tłuszczu podczas cardio',
        ],
        correct: 1,
        explanation: 'Glicerol działa przez tzw. hiperwodowanie — przed treningiem pomaga zatrzymać więcej wody w organizmie, przez co wolniej się odwadniasz podczas wysiłku. Szczególnie przydatny przy długich sesjach cardio lub treningu w upale. Może wydłużyć czas do wyczerpania nawet o 24%.',
      },
      {
        question: 'Kapsaicyna (substancja z papryczki chili) pomaga na treningu, bo:',
        options: [
          'Dostarcza dużo kalorii na wysiłek',
          'Zmniejsza odczuwanie bólu mięśni, dzięki czemu możesz ćwiczyć mocniej i dłużej',
          'Zwiększa poziom kortyzolu, który mobilizuje organizm',
          'Zawiera kofeinę',
        ],
        correct: 1,
        explanation: 'Kapsaicyna działa jak naturalny środek przeciwbólowy — zmniejsza odczuwanie bólu mięśni podczas wysiłku. W badaniach osoby przyjmujące 12 mg kapsaicyny przed treningiem wykonały więcej pracy niż grupa placebo — zarówno w bieganiu, jak i ćwiczeniach siłowych.',
      },
    ],
  },
  {
    id: 'macros',
    title: 'Jedzenie dla aktywnych',
    description: 'Podstawy żywienia dla osób ćwiczących — kalorie, białko, węgle i tłuszcze bez skomplikowanych teorii',
    icon: 'MacrosIcon',
    color: 'from-blue-500 to-cyan-600',
    questions: [
      {
        question: 'Ile kalorii dostarcza 1 gram tłuszczu?',
        options: ['2 kcal', '4 kcal', '7 kcal', '9 kcal'],
        correct: 3,
        explanation: 'Tłuszcz dostarcza 9 kcal na gram — ponad dwa razy więcej niż białko i węglowodany (po 4 kcal/g). Dlatego tłuste produkty są tak kaloryczne. To nie znaczy, że tłuszcz jest zły — jest niezbędny dla zdrowia hormonalnego.',
      },
      {
        question: 'Co to jest deficyt kaloryczny?',
        options: [
          'Jedzenie samych warzyw i owoców',
          'Spożywanie mniej kalorii niż spalasz — warunek konieczny do chudnięcia',
          'Unikanie węglowodanów w diecie',
          'Jedzenie tylko rano i wieczorem',
        ],
        correct: 1,
        explanation: 'Deficyt kaloryczny to po prostu: jesz mniej, niż spalasz. To jedyny mechanizm, który prowadzi do utraty tkanki tłuszczowej — niezależnie od diety (keto, wegetariańska, niskotłuszczowa). Optymalny deficyt dla ćwiczących to 300–500 kcal dziennie.',
      },
      {
        question: 'Które produkty są najlepszym źródłem białka dla ćwiczących?',
        options: [
          'Chleb, makaron, ryż',
          'Kurczak, ryby, jaja, twaróg, rośliny strączkowe',
          'Oliwa z oliwek, orzechy, awokado',
          'Warzywa i owoce',
        ],
        correct: 1,
        explanation: 'Kurczak, indyk, ryby, jaja, twaróg i rośliny strączkowe (soczewica, ciecierzyca, tofu) to najlepsze źródła białka. Zawierają wszystkie niezbędne aminokwasy potrzebne do budowy i regeneracji mięśni.',
      },
      {
        question: 'Ile wody dziennie powinien pić dorosły, aktywny fizycznie człowiek?',
        options: ['1 litr', '2–3 litry (plus więcej w dni treningowe)', '5–6 litrów', 'Wystarczy pić gdy jest się spragniony'],
        correct: 1,
        explanation: 'Aktywna osoba potrzebuje ok. 2–3 litrów wody dziennie jako minimum, a w gorące dni lub przy intensywnym treningu nawet więcej. Nawet 2% odwodnienia obniża wydolność i koncentrację. Kolor moczu to dobry wskaźnik — powinien być jasnosłomkowy.',
      },
      {
        question: 'Które tłuszcze warto jeść na co dzień?',
        options: [
          'Tłuszcze trans z fast foodów i margaryn',
          'Nienasycone tłuszcze z oliwy, orzechów, awokado i tłustych ryb',
          'Wyłącznie tłuszcze zwierzęce (masło, smalec)',
          'Żadne — tłuszcz trzeba całkowicie wyeliminować',
        ],
        correct: 1,
        explanation: 'Tłuszcze nienasycone (oliwa z oliwek, orzechy, awokado, łosoś, sardynki) wspierają zdrowie serca, mózgu i produkcję hormonów, w tym testosteronu. Tłuszcze trans (utwardzone oleje roślinne w fast foodach i gotowych wyrobach) są szkodliwe i warto ich unikać.',
      },
      {
        question: 'Co to jest indeks glikemiczny (IG)?',
        options: [
          'Ilość kalorii w produkcie',
          'Wskaźnik pokazujący jak szybko produkt podnosi poziom cukru we krwi po zjedzeniu',
          'Zawartość glukozy w gramach na 100 g produktu',
          'Ocena smaku produktu w skali 0–100',
        ],
        correct: 1,
        explanation: 'IG mówi jak szybko po zjedzeniu danego produktu rośnie cukier we krwi (skala 0–100). Niski IG (poniżej 55) = powolny wzrost cukru = dłuższa sytość. Wysoki IG = szybki wzrost i szybki spadek = szybciej wracasz głód. Dla ćwiczących: wysoki IG może być przydatny bezpośrednio po treningu.',
      },
      {
        question: 'Ile błonnika dziennie zaleca się dorosłym?',
        options: ['5–10 g', '25–30 g', '60–80 g', '100 g'],
        correct: 1,
        explanation: 'Zalecane spożycie błonnika to 25–30 g dziennie (EFSA). Błonnik spowalnia trawienie, przedłuża uczucie sytości i wspiera zdrowie jelit. Najlepsze źródła: warzywa, owoce, rośliny strączkowe, kasze, owies, nasiona chia.',
      },
      {
        question: 'Dlaczego węglowodany są ważne dla ćwiczących?',
        options: [
          'Są jedynym źródłem witamin i minerałów',
          'To główne paliwo dla mięśni podczas intensywnego treningu — bez nich szybciej tracisz siłę',
          'Pomagają spalać tłuszcz podczas cardio',
          'Węglowodany nie są ważne — wystarczy białko i tłuszcz',
        ],
        correct: 1,
        explanation: 'Węglowodany są magazynowane w mięśniach jako glikogen i to z niego mięśnie korzystają głównie podczas intensywnego treningu. Przy niedoborze glikogenu szybciej się męczysz, tracisz siłę i wolniej regenerujesz. Dla osób trenujących 3–5 razy w tygodniu zaleca się 3–6 g węglowodanów na kg masy ciała.',
      },
      {
        question: 'Co to są kwasy omega-3 i dlaczego warto je jeść?',
        options: [
          'To rodzaj cukru, który daje energię przed treningiem',
          'Zdrowe tłuszcze z ryb i orzechów włoskich, które zmniejszają stan zapalny i wspierają regenerację',
          'Aminokwasy niezbędne do budowy mięśni',
          'Witaminy rozpuszczalne w wodzie',
        ],
        correct: 1,
        explanation: 'Omega-3 (głównie EPA i DHA z tłustych ryb) zmniejszają stan zapalny po treningu, wspierają regenerację mięśni i zdrowie stawów. Zalecane spożycie ryb: 2–3 porcje tygodniowo. Dla osób nielubiących ryb: suplementacja olejem rybim (1–3 g EPA+DHA dziennie).',
      },
      {
        question: 'Czym różni się "masa mięśniowa" od "beztłuszczowej masy ciała"?',
        options: [
          'Nie ma żadnej różnicy, to te same pojęcia',
          'Beztłuszczowa masa ciała to mięśnie + kości + organy + woda — masa mięśniowa to tylko same mięśnie',
          'Masa mięśniowa to termin używany tylko przez kulturystów',
          'Beztłuszczowa masa ciała to wyłącznie tkanka mięśniowa',
        ],
        correct: 1,
        explanation: 'Beztłuszczowa masa ciała (FFM) obejmuje wszystko poza tłuszczem: mięśnie, kości, organy, wodę. Masa mięśniowa to sam mięsień. To ważne rozróżnienie np. przy obliczaniu zapotrzebowania na białko — często używa się beztłuszczowej masy ciała, żeby dostosować dawkę do faktycznej ilości aktywnej tkanki.',
      },
    ],
  },
  {
    id: 'supplementation',
    title: 'Przed i po treningu — co jeść?',
    description: 'Kiedy i co jeść wokół treningu, żeby wycisnąć z niego maksimum i szybciej się regenerować',
    icon: 'SupplIcon',
    color: 'from-purple-500 to-pink-600',
    questions: [
      {
        question: 'Kiedy najlepiej zjeść pełny posiłek przed treningiem siłowym?',
        options: ['Bezpośrednio przed wejściem na siłownię', '1–3 godziny przed treningiem', '6 godzin przed treningiem', 'Jedzenie przed treningiem nie ma znaczenia'],
        correct: 1,
        explanation: 'Posiłek mieszany (białko + węglowodany) zjedz 1–3 godziny przed treningiem. To daje czas na strawienie i zapewnia energię na trening. Bezpośrednio przed możesz zjeść małą przekąskę (banan, ryżowe wafle) jeśli jesteś głodny.',
      },
      {
        question: 'Co powinien zawierać dobry posiłek po treningu siłowym?',
        options: [
          'Tylko wodę i elektrolity',
          'Białko (20–40 g) + węglowodany — razem wspierają regenerację mięśni i uzupełnienie energii',
          'Wyłącznie tłuszcze — mają najwięcej kalorii',
          'Tylko owoce — naturalne cukry regenerują mięśnie',
        ],
        correct: 1,
        explanation: 'Po treningu mięśnie potrzebują białka (do naprawy i budowy włókien mięśniowych) oraz węglowodanów (do uzupełnienia glikogenu, czyli paliwa zużytego podczas treningu). Dobry przykład: ryż z kurczakiem, twaróg z owocami, shake białkowy z bananem.',
      },
      {
        question: 'Czy trzeba zjeść coś bezpośrednio po treningu (w ciągu 30 minut)?',
        options: [
          'Tak — musisz zjeść w ciągu 30 minut, inaczej stracisz efekty treningu',
          'Nie — masz ok. 2–3 godziny na zjedzenie posiłku po treningu',
          'Nie możesz jeść przez 2 godziny po treningu',
          'Liczy się tylko kolacja, niezależnie od godziny treningu',
        ],
        correct: 1,
        explanation: 'To mit, że po treningu jest "okno 30 minut". Badania pokazują, że masz spokojnie 2–3 godziny na zjedzenie posiłku po treningu. Ważniejsze jest całkowite spożycie białka i kalorii w ciągu całego dnia niż dokładna pora po treningu.',
      },
      {
        question: 'Ile białka warto zjeść po treningu siłowym?',
        options: ['5–10 g (pół szklanki mleka)', '20–40 g (np. 3 jajka lub porcja kurczaka)', '80–100 g naraz', 'Im więcej, tym lepiej'],
        correct: 1,
        explanation: 'Optymalna porcja białka po treningu to 20–40 g. Dla mniejszych osób wystarczy 20 g, dla większych lub po bardzo intensywnym treningu — do 40 g. Zjedzenie 100 g białka naraz nie daje proporcjonalnie lepszych efektów — organizm nie wchłonie tyle na raz do syntezy mięśni.',
      },
      {
        question: 'Czy można ćwiczyć na czczo (np. rano przed śniadaniem)?',
        options: [
          'Nie — to bardzo szkodliwe i zawsze prowadzi do utraty mięśni',
          'Tak — trening na czczo jest bezpieczny, choć może nie być optymalny dla siły i intensywności',
          'Tak, ale tylko cardio — na siłownię zawsze trzeba zjeść',
          'Tak, ale spalasz wtedy wyłącznie mięśnie, nie tłuszcz',
        ],
        correct: 1,
        explanation: 'Trening na czczo (np. poranny jogging) jest bezpieczny dla większości zdrowych osób. Może nie być optymalny dla bardzo intensywnych sesji siłowych — możesz mieć mniej siły. Przy treningu cardio niskiej intensywności różnica jest minimalna. Kluczowe jest to, co jesz w ciągu całego dnia.',
      },
      {
        question: 'Co warto pić podczas długiego treningu (powyżej 60 minut)?',
        options: [
          'Wyłącznie czystą wodę',
          'Wodę z elektrolitami (sód, potas) — szczególnie przy intensywnym wysiłku lub upale',
          'Napoje energetyczne z dużą ilością cukru',
          'Nic — picie podczas treningu zmniejsza wydolność',
        ],
        correct: 1,
        explanation: 'Podczas długiego lub intensywnego treningu wraz z potem tracisz elektrolity — głównie sód i potas. Sama woda ich nie uzupełnia. Możesz pić izotonik, wodę z elektrolitami lub po prostu zadbać o sól w posiłkach. Picie podczas treningu nie szkodzi — odwodnienie szkodzi.',
      },
      {
        question: 'Które węglowodany są lepsze przed treningiem?',
        options: [
          'Słodycze i napoje energetyczne — dają szybką energię',
          'Złożone węglowodany (ryż, kasza, owies, makaron) — dają stałą energię przez cały trening',
          'Nie ma żadnej różnicy — każdy węglowodan działa tak samo',
          'Węglowodany przed treningiem to błąd — tuczą',
        ],
        correct: 1,
        explanation: 'Złożone węglowodany (ryż, kasza, płatki owsiane, makaron) trawią się wolniej i dają stabilną energię przez cały trening. Cukry proste (słodycze, napoje) dają szybki zastrzyk energii, po którym często następuje spadek. Wyjątek: mała przekąska bezpośrednio przed treningiem — tu szybkie węglowodany (banan) są w porządku.',
      },
      {
        question: 'Po intensywnym treningu wytrzymałościowym (bieg, rower) jak najszybciej uzupełnić glikogen?',
        options: [
          'Zjeść dużo białka — buduje mięśnie i odbudowuje energię',
          'Zjeść węglowodany — ryż, makaron, ziemniaki, owoce — to uzupełni zapasy glikogenu w mięśniach',
          'Nic nie jeść przez 2 godziny — organizm sam się regeneruje',
          'Wypić tylko wodę z elektrolitami',
        ],
        correct: 1,
        explanation: 'Po długim cardio mięśnie są pozbawione glikogenu (ich głównego paliwa). Szybkie uzupełnienie węglowodanów (w ciągu 1–2h po treningu) przyspiesza regenerację — szczególnie ważne jeśli trenujesz ponownie tego samego dnia lub następnego dnia rano.',
      },
      {
        question: 'Czy odżywka białkowa (shake po treningu) jest konieczna?',
        options: [
          'Tak — bez shake\'a po treningu mięśnie nie rosną',
          'Nie — shake to tylko wygodne źródło białka, które możesz zastąpić normalnym jedzeniem',
          'Tak, ale tylko shake z kreatyny, nie z białka',
          'Nie — shake\'i są szkodliwe i nie warto ich używać',
        ],
        correct: 1,
        explanation: 'Odżywka białkowa to po prostu skoncentrowane białko w wygodnej formie. Możesz ją spokojnie zastąpić kurczakiem, jajami, twarogiem lub rybą. Shake jest przydatny jeśli masz problem z jedzeniem wystarczającej ilości białka z normalnych posiłków lub potrzebujesz szybkiej opcji po treningu.',
      },
      {
        question: 'Ile posiłków dziennie jest optymalne dla osoby trenującej?',
        options: [
          'Dokładnie 6 posiłków — nic więcej, nic mniej',
          '3–5 posiłków dziennie — co 3–5 godzin — to wystarczy dla większości ćwiczących',
          '1–2 duże posiłki dziennie (intermittent fasting)',
          'Liczy się tylko kalorii, ilość posiłków nie ma żadnego znaczenia',
        ],
        correct: 1,
        explanation: 'Dla osób ćwiczących 3–5 posiłków co 3–5 godzin to dobry schemat — pozwala regularnie dostarczać białko dla mięśni i utrzymać stabilny poziom energii. Intermittent fasting też może działać, ale wymaga staranniejszego planowania, żeby zmieścić odpowiednią ilość białka w oknie żywieniowym.',
      },
    ],
  },
  {
    id: 'advanced',
    title: 'Mity żywieniowe — prawda czy fałsz?',
    description: 'Obalamy najpopularniejsze mity o diecie, odchudzaniu i suplementach. Sprawdź co faktycznie mówi nauka!',
    icon: 'AdvancedIcon',
    color: 'from-amber-500 to-orange-600',
    questions: [
      {
        question: 'Czy jedzenie po 18:00 powoduje przybieranie na wadze?',
        options: [
          'Tak — po 18:00 kalorie odkładają się w tłuszcz',
          'Nie — liczy się całkowita ilość kalorii w ciągu dnia, nie pora ich jedzenia',
          'Tak, ale tylko węglowodany po 18:00 tuczą',
          'To zależy od znaku zodiaku i metabolizmu',
        ],
        correct: 1,
        explanation: 'To jeden z największych mitów. Organizm nie patrzy na zegarek — liczy się bilans kaloryczny przez całą dobę. Jeśli zjesz tyle ile spalasz, nie przytyjesz — niezależnie czy zjesz o 17:59 czy 18:01. Pora posiłku ma minimalne znaczenie metaboliczne.',
      },
      {
        question: 'Czy dieta tłuszczowa (np. keto) sprawia, że spalasz więcej tłuszczu?',
        options: [
          'Tak — jedząc tłuszcz, uczysz organizm spalać tłuszcz i automatycznie chudniesz',
          'Nie — chudniesz gdy masz deficyt kaloryczny, a nie dlatego że jesz tłuszcz lub unikasz węgli',
          'Tak, bo tłuszcz przyspiesza metabolizm',
          'Tak, ale tylko u mężczyzn',
        ],
        correct: 1,
        explanation: 'Dieta keto może działać świetnie — ale tylko dlatego, że pomaga niektórym osobom utrzymać deficyt kaloryczny (np. przez większą sytość). Sam fakt jedzenia tłuszczu nie "spala tłuszczu". Chudniesz zawsze z jednego powodu: spalasz więcej kalorii niż jesz.',
      },
      {
        question: 'Czy "detoks" (np. głodówka sokowa) jest potrzebny, żeby oczyścić organizm?',
        options: [
          'Tak — co jakiś czas trzeba oczyścić organizm z toksyn',
          'Nie — wątroba i nerki robią to 24/7 i żaden "detoks" nie przyspiesza tego procesu',
          'Tak, szczególnie po świętach i weekendach',
          'Tak, ale tylko detoks warzywny, nie sokowy',
        ],
        correct: 1,
        explanation: 'Wątroba, nerki, płuca i skóra oczyszczają organizm z toksyn non-stop — to ich główna funkcja. Nie ma żadnych badań naukowych potwierdzających, że głodówki sokowe czy "detoksy" pomagają w tym procesie. Mogą natomiast prowadzić do niedoborów i uczucia osłabienia.',
      },
      {
        question: 'Czy gluten jest szkodliwy dla zdrowych osób?',
        options: [
          'Tak — gluten szkodzi każdemu i powinien go unikać każdy',
          'Nie — gluten jest problemem tylko dla osób z celiakią lub nietolerancją glutenu',
          'Tak, szczególnie dla sportowców',
          'Tak, ale tylko pszeniczny — orkiszowy jest bezpieczny',
        ],
        correct: 1,
        explanation: 'Gluten szkodzi osobom z celiakią (choroba autoimmunologiczna), alergią na pszenicę lub nietolerancją glutenu. U zdrowych osób bez tych schorzeń gluten nie powoduje żadnych problemów. Dieta bezglutenowa bez wskazań medycznych nie przynosi korzyści, a może prowadzić do niedoborów.',
      },
      {
        question: 'Czy kreatyna to steryd anaboliczny?',
        options: [
          'Tak — kreatyna to legalny steryd',
          'Nie — kreatyna to naturalny związek produkowany przez organizm, który pomaga mięśniom pracować intensywniej',
          'Tak, dlatego jest zakazana w sporcie',
          'Tak, ale tylko w dużych dawkach',
        ],
        correct: 1,
        explanation: 'Kreatyna to naturalny związek obecny w mięśniach (i w mięsie), który pomaga w resyntezie energii (ATP) podczas intensywnych ćwiczeń. Nie ma nic wspólnego ze sterydami anabolicznymi. Jest legalną suplementacją (WADA jej nie zakazuje), bezpieczną i jedną z najlepiej przebadanych substancji ergogenicznych.',
      },
      {
        question: 'Czy suplementy mogą zastąpić zdrową dietę?',
        options: [
          'Tak — przy odpowiednich suplementach dieta nie ma znaczenia',
          'Nie — suplementy to dodatek do dobrej diety, nie zamiennik jedzenia',
          'Tak, szczególnie odżywki białkowe i multiwitaminy',
          'Tak, ale tylko dla sportowców wyczynowych',
        ],
        correct: 1,
        explanation: 'Suplementy — jak sama nazwa wskazuje — mają uzupełniać dietę, nie ją zastępować. Nawet najlepszy suplement nie wyrówna skutków złej diety, braku snu i nieaktywnego trybu życia. Podstawa to: dobre jedzenie, regularny trening, odpowiednia ilość snu. Suplementy są "wisienką na torcie".',
      },
      {
        question: 'Czy więcej białka zawsze oznacza więcej mięśni?',
        options: [
          'Tak — im więcej białka, tym szybciej rosną mięśnie',
          'Nie — po przekroczeniu ok. 2,2 g na kg masy ciała dodatkowe białko nie daje już lepszych efektów',
          'Tak, dlatego kulturyści jedzą po 500 g białka dziennie',
          'Nie — białko nie ma żadnego wpływu na wzrost mięśni',
        ],
        correct: 1,
        explanation: 'Badania pokazują, że efekty wzrostu mięśni "nasycają się" przy ok. 2,2 g białka na kg masy ciała dziennie. Jedzenie 3–4 g/kg nie da proporcjonalnie lepszych wyników. Nadmiar białka jest po prostu spalany jako energia. Ważniejsza jest regularność i jakość treningu.',
      },
      {
        question: 'Czy cardio jest lepsze od treningu siłowego na odchudzanie?',
        options: [
          'Tak — tylko cardio spala tłuszcz',
          'Nie — trening siłowy buduje mięśnie, które zwiększają metabolizm i spalają więcej kalorii przez całą dobę',
          'Tak, szczególnie bieganie na czczo',
          'Tylko trening siłowy działa — cardio nie spala tłuszczu',
        ],
        correct: 1,
        explanation: 'Najlepsza kombinacja to oba rodzaje treningu. Cardio spala kalorie podczas ćwiczeń, ale trening siłowy buduje mięśnie, które zwiększają podstawowe zapotrzebowanie kaloryczne (spalasz więcej nawet w spoczynku). Dla długoterminowej redukcji i utrzymania efektów trening siłowy jest równie ważny co cardio.',
      },
      {
        question: 'Czy można schudnąć bez liczenia kalorii?',
        options: [
          'Nie — liczenie kalorii to jedyna skuteczna metoda odchudzania',
          'Tak — jeśli naturalnie jesz mniej niż spalasz (np. przez ograniczenie przetworzonej żywności, regularność posiłków)',
          'Tak, ale tylko na diecie keto',
          'Nie — bez aplikacji do liczenia kalorii odchudzanie nie działa',
        ],
        correct: 1,
        explanation: 'Liczenie kalorii to skuteczne narzędzie, ale nie jedyne. Można schudnąć jedząc głównie produkty nieprzetworzone, regularnie, z dużą ilością białka i warzyw — naturalnie prowadzi to do deficytu kalorycznego bez liczenia. Liczenie kalorii jest szczególnie pomocne gdy brakuje efektów lub przy zaawansowanej redukcji.',
      },
      {
        question: 'Czy słodycze bezwzględnie muszą zniknąć z diety ćwiczącego?',
        options: [
          'Tak — słodycze to truciznna dla sportowców',
          'Nie — od czasu do czasu słodycze mieszczą się w zbilansowanej diecie i nie niszczą efektów treningu',
          'Tak, ale można je zastąpić wyłącznie owocami',
          'Nie — słodycze po treningu są wręcz wskazane dla każdego',
        ],
        correct: 1,
        explanation: 'Nie istnieje "zakazana" żywność — są tylko ilości. Zasada 80/20 (80% wartościowego jedzenia, 20% przyjemności) to zdrowe, długoterminowe podejście. Restrykcyjne zakazy prowadzą do napadów objadania się i porzucenia diety. Kluczowy jest bilans kaloryczny w skali tygodnia, nie skrupulatna kontrola każdego kęsa.',
      },
    ],
  },
]
