export const diets = [
  {
    id: '2000',
    calories: 2000,
    label: '2000 kcal',
    goal: 'Redukcja tkanki tłuszczowej',
    description: 'Plan dla sportowca na deficycie kalorycznym. Wysokie białko chroni masę mięśniową podczas redukcji.',
    bodyWeight: 80,
    macros: { protein: 160, carbs: 196, fat: 64 },
    perKg: { protein: 2.0, carbs: 2.45, fat: 0.8 },
    meals: [
      {
        name: 'Śniadanie',
        time: '7:00',
        items: [
          'Płatki owsiane (60g)',
          'Białko serwatkowe (25g)',
          'Mleko 2% (200ml)',
          'Banan (100g)',
          'Masło orzechowe (10g)',
        ],
        macros: { calories: 495, protein: 30, carbs: 60, fat: 15 },
      },
      {
        name: 'II Śniadanie',
        time: '10:30',
        items: [
          'Twaróg półtłusty (150g)',
          'Chleb razowy (2 kromki / 80g)',
          'Pomidor + ogórek',
        ],
        macros: { calories: 330, protein: 25, carbs: 35, fat: 10 },
      },
      {
        name: 'Obiad',
        time: '13:30',
        items: [
          'Pierś z kurczaka (200g)',
          'Ryż biały suchy (70g)',
          'Brokuły + papryka (200g)',
          'Oliwa z oliwek (1 łyżka)',
        ],
        macros: { calories: 600, protein: 50, carbs: 55, fat: 20 },
      },
      {
        name: 'Przekąska przed treningiem',
        time: '16:30',
        items: [
          'Jogurt grecki 0% (150g)',
          'Banan (80g)',
          'Migdały (15g)',
        ],
        macros: { calories: 232, protein: 15, carbs: 25, fat: 8 },
      },
      {
        name: 'Kolacja',
        time: '19:30',
        items: [
          'Dorsz lub mintaj (200g)',
          'Ziemniaki gotowane (150g)',
          'Sałatka z warzyw',
          'Oliwa z oliwek (1 łyżeczka)',
        ],
        macros: { calories: 343, protein: 40, carbs: 21, fat: 11 },
      },
    ],
  },
  {
    id: '2500',
    calories: 2500,
    label: '2500 kcal',
    goal: 'Utrzymanie masy / rekompozcyja',
    description: 'Plan dla regularnie trenującego sportowca. Balans między podtrzymaniem masy mięśniowej a dobrą energią na treningi.',
    bodyWeight: 80,
    macros: { protein: 160, carbs: 321, fat: 64 },
    perKg: { protein: 2.0, carbs: 4.0, fat: 0.8 },
    meals: [
      {
        name: 'Śniadanie',
        time: '7:00',
        items: [
          'Płatki owsiane (100g)',
          'Białko serwatkowe (25g)',
          'Mleko 2% (200ml)',
          'Banan (120g)',
          'Masło orzechowe (10g)',
        ],
        macros: { calories: 615, protein: 30, carbs: 90, fat: 15 },
      },
      {
        name: 'II Śniadanie',
        time: '10:30',
        items: [
          'Chleb razowy (3 kromki / 120g)',
          'Pierś z kurczaka gotowana (100g)',
          'Ser twarogowy (50g)',
          'Pomidor + ogórek',
        ],
        macros: { calories: 430, protein: 25, carbs: 60, fat: 10 },
      },
      {
        name: 'Obiad',
        time: '13:30',
        items: [
          'Pierś z kurczaka (200g)',
          'Makaron pełnoziarnisty suchy (110g)',
          'Passata pomidorowa (150g)',
          'Oliwa z oliwek (1 łyżka)',
          'Parmezan (15g)',
        ],
        macros: { calories: 740, protein: 50, carbs: 90, fat: 20 },
      },
      {
        name: 'Posiłek przed treningiem',
        time: '16:30',
        items: [
          'Ryż biały suchy (60g)',
          'Twaróg chudy (100g)',
          'Banan (80g)',
        ],
        macros: { calories: 332, protein: 20, carbs: 45, fat: 8 },
      },
      {
        name: 'Kolacja',
        time: '19:30',
        items: [
          'Łosoś (150g)',
          'Ziemniaki gotowane (200g)',
          'Sałatka z warzyw',
          'Oliwa z oliwek (1 łyżeczka)',
        ],
        macros: { calories: 383, protein: 35, carbs: 36, fat: 11 },
      },
    ],
  },
  {
    id: '3000',
    calories: 3000,
    label: '3000 kcal',
    goal: 'Budowanie masy mięśniowej',
    description: 'Plan na masie dla zaawansowanego sportowca. Bardzo wysoka podaż węglowodanów zapewnia energię na ciężkie treningi i wspiera regenerację.',
    bodyWeight: 80,
    macros: { protein: 160, carbs: 446, fat: 64 },
    perKg: { protein: 2.0, carbs: 5.6, fat: 0.8 },
    meals: [
      {
        name: 'Śniadanie',
        time: '7:00',
        items: [
          'Płatki owsiane (120g)',
          'Białko serwatkowe (25g)',
          'Mleko 2% (250ml)',
          'Banan (150g)',
          'Masło orzechowe (10g)',
        ],
        macros: { calories: 695, protein: 30, carbs: 110, fat: 15 },
      },
      {
        name: 'II Śniadanie',
        time: '10:30',
        items: [
          'Chleb razowy (4 kromki / 160g)',
          'Pierś z kurczaka gotowana (100g)',
          'Ser żółty (20g)',
          'Pomidor + sałata + ogórek',
          'Oliwa z oliwek (1 łyżeczka)',
        ],
        macros: { calories: 530, protein: 25, carbs: 85, fat: 10 },
      },
      {
        name: 'Obiad',
        time: '13:30',
        items: [
          'Ryż biały suchy (140g)',
          'Mielona wołowina chuda (200g)',
          'Papryka + cukinia (200g)',
          'Sos pomidorowy (100g)',
          'Oliwa z oliwek (1 łyżka)',
        ],
        macros: { calories: 860, protein: 50, carbs: 120, fat: 20 },
      },
      {
        name: 'Shake potreningowy',
        time: '17:00',
        items: [
          'Białko serwatkowe (25g)',
          'Banan (150g)',
          'Płatki owsiane (50g)',
          'Mleko 0,5% (200ml)',
        ],
        macros: { calories: 432, protein: 20, carbs: 70, fat: 8 },
      },
      {
        name: 'Kolacja',
        time: '19:30',
        items: [
          'Łosoś (150g)',
          'Ziemniaki gotowane (300g)',
          'Sałatka z warzyw',
          'Oliwa z oliwek (1 łyżeczka)',
        ],
        macros: { calories: 483, protein: 35, carbs: 61, fat: 11 },
      },
    ],
  },
]
